import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,readFile,writeFile,appendFile,rename,rm,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,sep,basename} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {demoState} from '../src/demo.mjs';
import {validate,evolve} from '../src/runtime.mjs';
import {planManagedMetrics,applyManagedMetrics,ensureManagedMetrics,refreshManagedMetrics,prepareManagedStep,runManagedStep,revokeManagedMetrics,enableObservationTeams} from '../src/managed-metrics.mjs';
import {locateSessions,verifySessionCandidate} from '../src/session-locator.mjs';
import {refreshStats,readStatsIndex,releaseStatsSession} from '../src/stats-collector.mjs';
import {queryStats,createStatsSnapshot,querySourceStatus} from '../src/stats-query.mjs';
import {MetadataJsonParser} from '../src/stats-json-stream.mjs';
const at=n=>new Date(Date.UTC(2026,9,7,10,n)).toISOString(),line=v=>JSON.stringify(v)+'\n';
const usage=(n,time=at(n))=>({type:'event_msg',timestamp:time,payload:{type:'token_count',info:{last_token_usage:{input_tokens:10*n,cached_input_tokens:4*n,output_tokens:2*n,reasoning_output_tokens:n,total_tokens:12*n},total_token_usage:{input_tokens:10*n,cached_input_tokens:4*n,output_tokens:2*n,reasoning_output_tokens:n,total_tokens:12*n}}}});
async function fixture(t){
  const root=await mkdtemp(join(tmpdir(),'runtime-managed-metrics-')),statePath=join(root,'state.json'),registryPath=join(root,'registry.json'),indexPath=join(root,'index.sqlite'),sessionRoot=join(root,'sessions'),observationRoot=join(root,'observations'),managedRoot=join(root,'managed'),state=demoState();
  state.schemaVersion=2;state.registry={registryId:'fixture-registry',registryPath,teamId:state.team.id,migrationId:'fixture-adopt',sourceSha256:'1'.repeat(64),sourceVersion:state.version,phase:'active',teamRevision:1,readyMemberIds:state.members.map(m=>m.id)};
  const registry={teams:[{id:state.team.id,revision:1,runtime:{statePath},members:state.members.map(m=>({id:m.id,role:m.role,lifecycle:m.lifecycle,binding:{hostId:m.binding.hostId,threadId:m.binding.threadId,revision:1}}))}]};await mkdir(sessionRoot);await mkdir(observationRoot);await writeFile(statePath,JSON.stringify(validate(state)));await writeFile(registryPath,JSON.stringify(registry));
  const db=new DatabaseSync(indexPath);db.exec('CREATE TABLE threads(id TEXT PRIMARY KEY, rollout_path TEXT, created_at INTEGER, updated_at INTEGER, title TEXT, first_user_message TEXT)');const insert=db.prepare('INSERT INTO threads VALUES(?,?,?,?,?,?)');const paths={};for(const m of state.members){const path=join(sessionRoot,m.id+'.jsonl');paths[m.id]=path;await writeFile(path,line({type:'session_meta',payload:{id:m.binding.threadId,instructions:'PRIVATE_FIXTURE_NOT_SELECTED'}}));insert.run(m.binding.threadId,path,Date.parse('2026-09-04T00:00:00.000Z')/1000,Date.parse(at(0))/1000,'PRIVATE_TITLE','PRIVATE_PROMPT');}insert.run('unrelated-thread',join(root,'unapproved.jsonl'),1,1,'PRIVATE_OTHER_TITLE','PRIVATE_OTHER_PROMPT');db.close();
  const read=async path=>validate(JSON.parse(await readFile(path))),request={authorizationRef:'fixture:explicit selected-team metadata grant',hostId:'fixture-host',managedRoot,indexPath,sessionRoots:[sessionRoot],observationRoot,observationTeams:[state.team.id,'approved-other-team'],historicalFrom:'2026-09-01T00:00:00.000Z',expiresAt:'2026-11-01T00:00:00.000Z',legacyManifestPath:null,activityManifests:[]},options={read,now:()=>at(0)};
  const plan=await planManagedMetrics(statePath,request,options);await applyManagedMetrics(plan,{read});const policyPath=join(managedRoot,'policy.json'),cache=join(managedRoot,'cache'),refresh=(n=5,extra={})=>refreshManagedMetrics(policyPath,{read,now:()=>at(n),asOf:at(n),...extra});
  t.after(async()=>{releaseStatsSession(cache);const p=await realpath(root),parent=await realpath(tmpdir());assert.ok(p.startsWith(parent+sep)&&/^runtime-managed-metrics-/.test(basename(p)));await rm(p,{recursive:true,force:true,maxRetries:3});});return {root,state,statePath,registryPath,registry,indexPath,paths,sessionRoot,observationRoot,managedRoot,policyPath,cache,request,read,plan,refresh};
}
test('exact sqlite metadata lookup excludes unrelated rows/body; enabled refresh ingests actual new usage and repeated ensure stays identical',async t=>{
  const f=await fixture(t),ids=f.state.members.map(m=>m.binding.threadId),rows=await locateSessions(f.indexPath,ids);assert.equal(rows.length,6);assert.ok(!JSON.stringify(rows).includes('PRIVATE_'));const header=await verifySessionCandidate(rows[0],[f.sessionRoot]);assert.ok(!JSON.stringify(header).includes('PRIVATE_'));await f.refresh();
  await appendFile(f.paths['worker-04'],line({type:'response_item',timestamp:at(1),payload:{type:'function_call_output',name:'create_thread',output:'PRIVATE_INHERITED_OUTPUT'}})+line({type:'response_item',timestamp:at(1).replace('.000Z','.0Z'),payload:{type:'function_call',call_id:'real-call',name:'functions.exec'}})+line({type:'response_item',timestamp:at(2),payload:{type:'function_call_output',call_id:'real-call',output:'unknown'}})+line({type:'response_item',timestamp:at(3),payload:{type:'function_call_output',call_id:'real-call',output:'still unknown'}})+line(usage(1)));const index=await f.refresh();assert.equal(index.managedPolicy.status,'active');const q=await queryStats(f.cache,{view:'token',memberId:'worker-04',preset:'all'},{now:Date.parse(at(5))});assert.equal(q.data.summary.token.nativeTotal.total.known,12);
  const native=index.sources.find(s=>s.kind==='codex-jsonl'&&s.diagnostics.some(d=>d.code==='native_call_identity_missing'));assert.equal(native.status,'fresh');assert.ok(native.diagnostics.some(d=>d.code==='native_unpaired_response_conflict'));assert.ok(!JSON.stringify(q).includes('PRIVATE_'));
  const before=await readFile(join(f.managedRoot,'manifest.json')),second=await ensureManagedMetrics(f.policyPath,{read:f.read,now:()=>at(6),asOf:at(6)});assert.equal(second.changed,false);assert.deepEqual(await readFile(second.manifestPath),before);assert.equal((await applyManagedMetrics(f.plan,{read:f.read})).status,'unchanged');
});
test('large compacted arrays validate skipped body keys with bounded live metadata, retained metadata and duplicate keys remain strict',()=>{
  const parser=new MetadataJsonParser();parser.push(JSON.stringify({type:'compacted',payload:{replacement_history:Array.from({length:10000},()=>({role:'user',content:[{type:'text',text:'PRIVATE_BODY'}]}))}}));assert.equal(parser.finish().type,'compacted');assert.ok(parser.metadataBytes<65536);assert.ok(!JSON.stringify(parser.projected).includes('PRIVATE_BODY'));
  assert.throws(()=>new MetadataJsonParser().push('{"type":"compacted","payload":{"x":1,"x":2}}'),{code:'source_duplicate_key'});
  assert.throws(()=>new MetadataJsonParser().push(JSON.stringify({type:'x'.repeat(65536)})),{code:'source_metadata_limit'});
});
test('new ready member uses actual admission time, not amended old round; unknown index identity is skipped without unrelated raw collection',async t=>{
  const f=await fixture(t);await f.refresh();const m={id:'new-worker',name:'New Worker',role:'Worker',lifecycle:'active',binding:{status:'bound',hostId:'fixture-host',threadId:'new-thread'}};f.state.members.push(m);f.state.registry.readyMemberIds.push(m.id);f.state.registry.teamRevision=2;f.registry.teams[0].revision=2;f.registry.teams[0].members.push({...m,binding:{hostId:'fixture-host',threadId:'new-thread',revision:1}});
  f.state=evolve(f.state,{id:'admit-new',type:'admitRegistryMember',actor:'manager',caller:{hostId:'fixture-host',threadId:'fixture-manager'},at:at(2),source:{kind:'fixture',ref:'actual-synthetic-admission'},roundId:'round-demo',memberId:m.id},f.state.version);await writeFile(f.statePath,JSON.stringify(f.state));await writeFile(f.registryPath,JSON.stringify(f.registry));const path=join(f.sessionRoot,'new.jsonl');await writeFile(path,line({type:'session_meta',payload:{id:'new-thread'}})+line(usage(1,at(1)))+line(usage(2,at(3))));const db=new DatabaseSync(f.indexPath);db.prepare('INSERT INTO threads VALUES(?,?,?,?,?,?)').run('new-thread',path,Date.parse(at(1))/1000,Date.parse(at(3))/1000,'private','private');db.close();
  await f.refresh(4);const journal=JSON.parse(await readFile(join(f.managedRoot,'journal.json'))),epoch=journal.epochs.find(e=>e.memberId===m.id);assert.equal(epoch.from,at(2));const q=await queryStats(f.cache,{view:'token',memberId:m.id,preset:'all'},{now:Date.parse(at(4))});assert.equal(q.data.summary.token.nativeTotal.total.known,24);
  await rename(path,path+'.old');await writeFile(path,line({type:'session_meta',payload:{id:'foreign-thread'}})+line(usage(3)));await f.refresh(5);const status=await querySourceStatus(f.cache,f.state.members,{preset:'all'},{now:Date.parse(at(5))});assert.ok(status.rows.find(r=>r.memberId===m.id).metrics.token.problems.includes('managed_candidate_identity_mismatch'));assert.equal((await queryStats(f.cache,{view:'token',memberId:m.id,preset:'all'},{now:Date.parse(at(5))})).data.summary.token.nativeTotal.total.known,24);
});
test('same-path rotation and indexed new path replace one source; immutable snapshot never drifts',async t=>{
  const f=await fixture(t);await appendFile(f.paths['worker-04'],line(usage(1)));await f.refresh();const wall=Date.now(),old=await createStatsSnapshot(f.cache,{now:wall});await rename(f.paths['worker-04'],f.paths['worker-04']+'.old');await writeFile(f.paths['worker-04'],line({type:'session_meta',payload:{id:'fixture-worker-04'}})+line(usage(2)));await f.refresh(6);
  const newer=join(f.sessionRoot,'new-path.jsonl');await rename(f.paths['worker-04'],newer);const db=new DatabaseSync(f.indexPath);db.prepare('UPDATE threads SET rollout_path=? WHERE id=?').run(newer,'fixture-worker-04');db.close();await f.refresh(7);const q=await queryStats(f.cache,{view:'token',memberId:'worker-04',preset:'all'},{now:Date.parse(at(7))});assert.equal(q.data.summary.token.nativeTotal.total.known,24);assert.equal((await queryStats(f.cache,{view:'token',memberId:'worker-04',preset:'all',baseSnapshotId:old.baseSnapshotId},{now:wall+1000})).data.summary.token.nativeTotal.total.known,12);
  const manifest=JSON.parse(await readFile(join(f.managedRoot,'manifest.json')));assert.equal(manifest.sources.filter(s=>s.kind==='codex-jsonl'&&s.bindings[0].memberId==='worker-04').length,1);
});
test('in-flight real step survives actual new member admission and submitted→approved keeps original producer history',async t=>{
  const f=await fixture(t),request={hostId:'fixture-host',threadId:'fixture-worker-04',taskId:'T-4',roundId:'round-demo',stepId:'bounded-operation',evidenceRef:'fixture:actual-operation'};let entered,release,effects=0;const started=new Promise(r=>entered=r),gate=new Promise(r=>release=r);const entry=await prepareManagedStep(f.policyPath,request,{read:f.read,now:()=>at(1),asOf:at(1)}),before=await readFile(entry.manifestPath);
  const running=runManagedStep(f.policyPath,request,join(f.root,'step.json'),[process.execPath,'-e',''],{read:f.read,now:()=>at(4),asOf:at(3),operation:async()=>{effects++;entered();await gate;return {exitCode:0,signal:null,errorCode:null};}});await started;
  const added={id:'parallel-new',name:'Parallel new',role:'Worker',lifecycle:'active',binding:{status:'bound',hostId:'fixture-host',threadId:'parallel-thread'}};f.state.members.push(added);f.state.registry.readyMemberIds.push(added.id);f.state.registry.teamRevision=2;f.registry.teams[0].revision=2;f.registry.teams[0].members.push({...added,binding:{hostId:'fixture-host',threadId:'parallel-thread',revision:1}});f.state=evolve(f.state,{id:'admit-parallel',type:'admitRegistryMember',actor:'manager',caller:{hostId:'fixture-host',threadId:'fixture-manager'},at:at(4),source:{kind:'fixture',ref:'parallel-admission'},roundId:'round-demo',memberId:added.id},f.state.version);await writeFile(f.statePath,JSON.stringify(f.state));await writeFile(f.registryPath,JSON.stringify(f.registry));
  await ensureManagedMetrics(f.policyPath,{read:f.read,now:()=>at(4),asOf:at(4)});assert.deepEqual(await readFile(entry.manifestPath),before);release();await running;assert.equal(effects,1);
  f.state=evolve(f.state,{id:'submit-step-task',type:'submit',actor:'worker-04',at:at(5),source:{kind:'fixture',ref:'completed-step'},roundId:'round-demo',taskId:'T-4',summary:'Synthetic submitted work'},f.state.version);await writeFile(f.statePath,JSON.stringify(f.state));await f.refresh(6);const steps=await queryStats(f.cache,{view:'steps',taskId:'T-4',memberId:'worker-04',preset:'all'},{now:Date.parse(at(6))});assert.equal(steps.data.rows.filter(r=>r.stepId==='bounded-operation').length,1);assert.deepEqual(await readFile(entry.manifestPath),before);
  f.state=evolve(f.state,{id:'review-step',type:'review',actor:'manager',at:at(7),source:{kind:'fixture',ref:'review'},roundId:'round-demo',taskId:'T-4'},f.state.version);f.state=evolve(f.state,{id:'approve-step',type:'approve',actor:'manager',at:at(8),source:{kind:'fixture',ref:'accept'},roundId:'round-demo',taskId:'T-4',summary:'Accepted',evidence:['fixture:accept']},f.state.version);await writeFile(f.statePath,JSON.stringify(f.state));await f.refresh(9);assert.equal((await queryStats(f.cache,{view:'steps',taskId:'T-4',memberId:'worker-04',preset:'all'},{now:Date.parse(at(9))})).data.rows.filter(r=>r.stepId==='bounded-operation').length,1);
});
test('revoke refuses new reads; last-good uses collector lock, independent MCP allowlist preserves legacy',async t=>{
  const f=await fixture(t);await appendFile(f.paths['worker-04'],line(usage(1)));await f.refresh();const allow=join(f.root,'allow.json');await writeFile(allow,JSON.stringify({schemaVersion:1,observedTeams:['legacy-video']}));const enabled=await enableObservationTeams(allow,[f.policyPath]);assert.ok(enabled.enabled.includes('legacy-video'));assert.ok(enabled.enabled.includes(f.state.team.id));
  let entered,release;const reached=new Promise(r=>entered=r),gate=new Promise(r=>release=r);const pending=f.refresh(6,{beforeCommit:async()=>{entered();await gate;}});await reached;await assert.rejects(revokeManagedMetrics(f.policyPath),{code:'EEXIST'});release();await pending;await revokeManagedMetrics(f.policyPath);const blocked=await f.refresh(7);assert.equal(blocked.readEvidence.readBytes,0);assert.equal(blocked.managedPolicy.status,'revoked');assert.equal(JSON.parse(await readFile(allow)).observedTeams.length,2);assert.equal((await queryStats(f.cache,{view:'token',memberId:'worker-04',preset:'all'},{now:Date.parse(at(7))})).data.summary.token.nativeTotal.total.known,12);
});
test('noncooperating revocation at beforeCommit cannot publish new contribution',async t=>{
  const f=await fixture(t);await appendFile(f.paths['worker-04'],line(usage(1)));await f.refresh();await appendFile(f.paths['worker-04'],line(usage(2)));const changed=await f.refresh(6,{beforeCommit:async()=>{const p=JSON.parse(await readFile(f.policyPath));p.status='revoked';p.revision++;await writeFile(f.policyPath,JSON.stringify(p));}});assert.equal(changed.managedPolicy.status,'revoked');assert.equal((await queryStats(f.cache,{view:'token',memberId:'worker-04',preset:'all'},{now:Date.parse(at(6))})).data.summary.token.nativeTotal.total.known,12);
});
test('real expiry cannot be bypassed with historical cutoff; direct managed-manifest refresh obeys policy and keeps last-good',async t=>{
  const f=await fixture(t);await appendFile(f.paths['worker-04'],line(usage(1)));await f.refresh();const expiry='2026-11-01T00:00:00.001Z',index=await refreshManagedMetrics(f.policyPath,{read:f.read,now:()=>expiry,asOf:expiry,locate:async()=>{throw Error('must not query index');}});assert.equal(index.managedPolicy.status,'expired');assert.equal(index.readEvidence.readBytes,0);assert.equal((await queryStats(f.cache,{view:'token',memberId:'worker-04',preset:'all'},{now:Date.parse(expiry)})).data.summary.token.nativeTotal.total.known,12);
  const direct=await refreshStats(join(f.managedRoot,'manifest.json'),f.cache,{read:f.read,now:()=>expiry,asOf:expiry});assert.equal(direct.managedPolicy.status,'expired');assert.equal(direct.readEvidence.readBytes,0);await assert.rejects(ensureManagedMetrics(f.policyPath,{read:f.read,now:()=>expiry,asOf:at(5)}),/managed_policy_expired/);
});
test('stale plan and true concurrent ensure refuse, index file failure keeps prior contribution with explicit gap',async t=>{
  const f=await fixture(t);await appendFile(f.paths['worker-04'],line(usage(1)));await f.refresh();const stale=await planManagedMetrics(f.statePath,{...f.request,managedRoot:join(f.root,'other-managed')},{read:f.read,now:()=>at(6)});f.state.registry.teamRevision++;f.registry.teams[0].revision++;await writeFile(f.statePath,JSON.stringify(f.state));await writeFile(f.registryPath,JSON.stringify(f.registry));await assert.rejects(applyManagedMetrics(stale,{read:f.read}),/managed_plan_stale/);
  let entered,release;const reached=new Promise(r=>entered=r),gate=new Promise(r=>release=r);const first=ensureManagedMetrics(f.policyPath,{read:f.read,now:()=>at(7),asOf:at(7),locate:async(...args)=>{entered();await gate;return locateSessions(...args);}});await reached;await assert.rejects(ensureManagedMetrics(f.policyPath,{read:f.read,now:()=>at(7),asOf:at(7)}),{code:'EEXIST'});release();await first;
  await rename(f.indexPath,f.indexPath+'.saved');await f.refresh(8);const health=await querySourceStatus(f.cache,f.state.members,{preset:'all'},{now:Date.parse(at(8))});assert.ok(health.rows.find(r=>r.memberId==='worker-04').metrics.token.problems.includes('managed_index_unavailable'));assert.equal((await queryStats(f.cache,{view:'token',memberId:'worker-04',preset:'all'},{now:Date.parse(at(8))})).data.summary.token.nativeTotal.total.known,12);
});
test('exit and rebind close old epoch at last seen, retain old data and exclude cached future/unproven records',async t=>{
  const f=await fixture(t);await appendFile(f.paths['worker-04'],line(usage(1))+line(usage(2,at(6))));await f.refresh(5);
  const member=f.state.members.find(m=>m.id==='worker-04'),native=f.registry.teams[0].members.find(m=>m.id===member.id);member.binding.threadId='replacement-thread';native.binding.threadId='replacement-thread';native.binding.revision=2;f.state.registry.teamRevision++;f.registry.teams[0].revision++;await writeFile(f.statePath,JSON.stringify(f.state));await writeFile(f.registryPath,JSON.stringify(f.registry));const path=join(f.sessionRoot,'replacement.jsonl');await writeFile(path,line({type:'session_meta',payload:{id:'replacement-thread'}})+line(usage(5,at(2)))+line(usage(1,at(9))));const db=new DatabaseSync(f.indexPath);db.prepare('INSERT INTO threads VALUES(?,?,?,?,?,?)').run('replacement-thread',path,Date.parse(at(1))/1000,Date.parse(at(9))/1000,'private','private');db.close();
  await f.refresh(8);let journal=JSON.parse(await readFile(join(f.managedRoot,'journal.json'))),epochs=journal.epochs.filter(e=>e.memberId===member.id);assert.equal(epochs.find(e=>e.bindingRevision===1).to,at(5));assert.equal(epochs.find(e=>e.bindingRevision===2).from,at(8));const q=await queryStats(f.cache,{view:'token',memberId:member.id,preset:'all'},{now:Date.parse(at(8))});assert.equal(q.data.summary.token.nativeTotal.total.known,12);
  await f.refresh(10);assert.equal((await queryStats(f.cache,{view:'token',memberId:member.id,preset:'all'},{now:Date.parse(at(10))})).data.summary.token.nativeTotal.total.known,24);member.lifecycle='exited';native.lifecycle='exited';f.state.registry.teamRevision++;f.registry.teams[0].revision++;await writeFile(f.statePath,JSON.stringify(f.state));await writeFile(f.registryPath,JSON.stringify(f.registry));await f.refresh(11);journal=JSON.parse(await readFile(join(f.managedRoot,'journal.json')));assert.equal(journal.epochs.find(e=>e.memberId===member.id&&e.bindingRevision===2).to,at(10));assert.equal((await queryStats(f.cache,{view:'token',memberId:member.id,preset:'all'},{now:Date.parse(at(11))})).data.summary.token.nativeTotal.total.known,24);
});
test('shared permitted TC root ignores other team/unknown bindings; snapshot cutoff omits future dates',async t=>{
  const f=await fixture(t);await mkdir(join(f.observationRoot,'2026-10-07'));const event=(team,member,thread)=>({schemaVersion:1,eventId:randomUUID(),startedAt:at(1),completedAt:at(2),durationMs:60000,tool:'team_context.read',registryId:'fixture-registry',teamId:team,memberId:member,role:'Worker',hostId:'fixture-host',threadId:thread,memberStatus:'active',identitySource:'registry-at-call-start',reason:'resume',reasonSource:'agent-declared',outcome:'matched',errorCode:null,policyRevision:2,runtimeRevision:null,runtimeRevisionSource:'unknown'});
  const own=event(f.state.team.id,'worker-04','fixture-worker-04'),other=event('approved-other-team','foreign','foreign'),unknown=event(f.state.team.id,'unknown','unknown');for(const e of [own,other,unknown])await writeFile(join(f.observationRoot,'2026-10-07',e.eventId+'.json'),line(e));const index=await f.refresh(5),root=index.sources.find(s=>s.kind==='team-context-root');assert.equal(root.status,'fresh');assert.equal(root.foreignEventsSkipped,1);assert.equal(root.unknownBindingsSkipped,1);assert.equal((await queryStats(f.cache,{view:'mcp',memberId:'worker-04',preset:'all'},{now:Date.parse(at(5))})).data.summary.mcp[1].calls,1);
});
test('real rework transition permits an owned command once, new submit retains it; submitted/reviewing/blocked and other Worker stay fenced',async t=>{
 const f=await fixture(t),task='T-4',request={hostId:'fixture-host',threadId:'fixture-worker-04',taskId:task,roundId:'round-demo',stepId:'actual-rework',evidenceRef:'fixture:authorized-rework'},source={kind:'fixture',ref:'actual-lifecycle'};
 const event=(type,n,actor='manager',extra={})=>{f.state=evolve(f.state,{id:type+'-'+n,type,actor,at:at(n),source,roundId:'round-demo',taskId:task,...extra},f.state.version);return writeFile(f.statePath,JSON.stringify(f.state));};
 await event('submit',1,'worker-04',{summary:'v1'});await event('review',2);await event('rework',3,'manager',{summary:'actual required correction'});
 const receipt=join(f.root,'rework-step.json'),marker=join(f.root,'effects.txt'),command=[process.execPath,'-e',"require('node:fs').appendFileSync(process.argv[1],'once\\n')",marker],options={read:f.read,now:()=>at(4),asOf:at(4)};
 await runManagedStep(f.policyPath,request,receipt,command,options);const replay=await runManagedStep(f.policyPath,request,receipt,command,options);assert.equal(replay.replayed,true);assert.equal(await readFile(marker,'utf8'),'once\n');
 await assert.rejects(prepareManagedStep(f.policyPath,{...request,threadId:'fixture-worker-03'},options));await event('submit',5,'worker-04',{summary:'rework complete'});await f.refresh(6);assert.ok((await queryStats(f.cache,{view:'steps',taskId:task,preset:'all'},{now:Date.parse(at(6))})).data.rows.some(r=>r.stepId==='actual-rework'&&r.status==='declared-completed'));
 for(const [status,n] of [['submitted',6],['reviewing',7],['blocked',8]]){if(status==='reviewing')await event('review',n);if(status==='blocked')await event('block',n,'manager',{summary:'blocked review'});await assert.rejects(prepareManagedStep(f.policyPath,request,{read:f.read,now:()=>at(n),asOf:at(n)}),/managed_task_not_executing/);}
});
