import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm,realpath,unlink} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,sep} from 'node:path';
import {createState,evolve} from '../src/runtime.mjs';
import {inboxRuntime} from '../src/manager-inbox.mjs';
import {validateInboxRequest,digest} from '../src/manager-inbox-contract.mjs';
import {noticeRuntime} from '../src/notice-runtime.mjs';
import {spawn} from 'node:child_process';

const at='2026-10-09T00:00:00.000Z',source={kind:'fixture',ref:'isolated E05 behavior; no native sender'},ok=r=>{assert.notEqual(r.status,'error',JSON.stringify(r));return r;};
async function fixture(t,{submitted=false}={}){
 const root=await realpath(await mkdtemp(join(tmpdir(),'e05-core-'))),statePath=join(root,'state.json'),registryPath=join(root,'registry.json');t.after(async()=>{const parent=await realpath(tmpdir());assert.ok(root.startsWith(parent+sep));await rm(root,{recursive:true,force:true,maxRetries:3});});
 const member=(id,role)=>({id,name:id,role,lifecycle:'active',binding:{status:'bound',hostId:'fixture-host',threadId:'fixture-'+id}});let state=createState({teamId:'team',name:'Team',source,members:[member('m','Manager'),member('l','Liaison'),member('w','Worker'),member('w2','Worker')]},at);
 for(const e of [{id:'open',type:'openRound',roundId:'r',title:'Round'},{id:'assign',type:'assign',roundId:'r',taskId:'t',title:'Task',workerId:'w',required:true,assignedAt:at},{id:'assign2',type:'assign',roundId:'r',taskId:'t2',title:'Task2',workerId:'w2',required:true,assignedAt:at},...(submitted?[{id:'submit-1',type:'submit',roundId:'r',taskId:'t',summary:'First formal',actor:'w'}]:[])])state=evolve(state,{actor:'m',at,source,...e},state.version);
 state={...state,schemaVersion:2,registry:{registryId:'registry',registryPath,teamId:'team',migrationId:'migration',sourceSha256:'a'.repeat(64),sourceVersion:state.version,phase:'active',teamRevision:1,readyMemberIds:['m','l','w','w2']}};
 const native={registryId:'registry',teams:[{id:'team',revision:1,leaderMemberId:'m',runtime:{statePath},members:state.members.map(m=>({...m,binding:{...m.binding,revision:1}}))}]};await writeFile(statePath,JSON.stringify(state));await writeFile(registryPath,JSON.stringify(native));
 const options={at,exporter:async s=>({registryId:'registry',teamId:'team',teamRevision:s.registry.teamRevision,migrationId:'migration',statePath,members:s.members,readyMemberIds:s.registry.readyMemberIds})};let n=0;
 const req=(action,extra={},who='m',operation_id='operation-'+(++n))=>({action,actor_host_id:'fixture-host',actor_thread_id:'fixture-'+who,team_id:'team',reason:'manual',...(action==='status'&&!extra.operation_id?{}:{operation_id}),...extra});
 const call=(r,opts={})=>inboxRuntime({statePath,registryPath,request:r,options:{...options,...opts}}),ledger=()=>readFile(statePath+'.manager-inbox.json','utf8').then(JSON.parse),raw=()=>readFile(statePath,'utf8').then(JSON.parse);
 const ctl=async(command,extra={})=>{const l=command==='init'?null:await ledger();return ok(await call(req('control',{command,authorization_ref:'fixture explicit authority',...(l?{expected_control_revision:l.controlRevision}:{expected_absent:true,expected_state_version:(await raw()).version,team_revision:1}),...extra})));};
 await ctl('init');
 const enable=async()=>{await ctl('set_mode',{mode:'queue_first',protocol_loaded:['m','w','w2'].map(member_id=>({member_id,binding_revision:1,evidence_ref:'fixture loaded'}))});await ctl('resume_claims');};
 const cp=async(extra={})=>{const l=await ledger();return ok(await call(req('checkpoint',{run_id:'run',expected_control_revision:l.controlRevision,trigger:'step_complete',...extra})));};
 const post=(seq,extra={},who='w')=>call(req('post',{message:{kind:'progress',message_id:'message-'+seq,round_id:'r',task_id:who==='w2'?'t2':'t',step_id:'step',producer_seq:seq,summary:'Report '+seq,evidence:[],...extra}},who));
 const claim=async snapshot=>{const l=await ledger(),i=snapshot.items[0];return ok(await call(req('claim',{run_id:'run',generation:l.consumer.generation,expected_control_revision:l.controlRevision,expected_work_id:l.activeWorkId,checkpoint_id:snapshot.checkpointId,item_id:i.itemId,payload_seq:i.payloadSeq,boundary_ref:'actual safe boundary'})));};
 const resolve=async(c,disposition,extra={})=>{const l=await ledger();return call(req('resolve',{run_id:'run',generation:l.consumer.generation,expected_control_revision:l.controlRevision,expected_work_id:l.activeWorkId,item_id:c.claim.itemId,claim_id:c.claim.id,disposition,reason_ref:'fixture actual decision',...extra}));};
 const event=async(type,extra={},actor='m')=>{let s=await raw();s=evolve(s,{id:'event-'+(++n),type,actor,at,source,roundId:'r',taskId:'t',...extra},s.version);await writeFile(statePath,JSON.stringify(s));return s.events.at(-1);};
 return {root,statePath,registryPath,native,options,req,call,ledger,raw,ctl,enable,cp,post,claim,resolve,event};
}
const userWork=()=>({work_id:'discussion',kind:'user-work',task_ref:null,user_work_ref:'actual user discussion',authorization_ref:'original authority',step_id:'write-document',phase:'active',next_action:{kind:'write-document',target_ref:'approved artifact'},evidence_refs:[],last_effect:{operation_ref:null,status:'not-started',evidence_ref:null},continuation_revision:0});

test('R-G actual child exits at six intent/business/projection boundaries; only exact ended-child token locks cleaned and original operation recovers',async t=>{
 for(const phase of ['before-review-intent','after-review-intent','before-business','after-business','before-review-projection','after-review-projection']){
  const f=await fixture(t,{submitted:true});await f.enable();const c=await f.claim(await f.cp()),r=f.req('start_review',{run_id:'run',generation:c.claim.generation,claim_id:c.claim.id,expected_state_version:(await f.raw()).version}),token='a'.repeat(32),foreign=join(f.root,'unrelated.lock');await writeFile(foreign,'do not delete');
  const script=`import {inboxRuntime} from ${JSON.stringify(new URL('../src/manager-inbox.mjs',import.meta.url).href)};import {ownedLocks} from ${JSON.stringify(new URL('../src/notice-adapter.mjs',import.meta.url).href)};const options={at:${JSON.stringify(at)},exporter:async s=>({registryId:'registry',teamId:'team',teamRevision:s.registry.teamRevision,migrationId:'migration',statePath:${JSON.stringify(f.statePath)},members:s.members,readyMemberIds:s.registry.readyMemberIds}),lockRunner:ownedLocks(${JSON.stringify(token)}),fault:p=>{if(p===${JSON.stringify(phase)})process.exit(73);}};await inboxRuntime({statePath:${JSON.stringify(f.statePath)},registryPath:${JSON.stringify(f.registryPath)},request:${JSON.stringify(r)},options});`;
  const child=spawn(process.execPath,['--input-type=module','-e',script],{shell:false,windowsHide:true,stdio:['ignore','pipe','pipe']});let stderr='';child.stderr.on('data',b=>stderr+=b);const exit=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('close',resolve);});assert.equal(exit,73,phase);
  const allowed=new Set([f.registryPath+'.lock',f.statePath+'.lock',f.statePath+'.manager-inbox.json.lock']);const owners=stderr.trim().split('\n').map(s=>{try{return JSON.parse(s).e03Lock;}catch{return null;}}).filter(Boolean);assert.equal(owners.length,3);
  for(const owner of owners){assert.equal(owner.pid,child.pid);assert.equal(owner.token,token);assert.ok(allowed.has(owner.path)&&owner.path.startsWith(f.root+sep));const actual=JSON.parse(await readFile(owner.path));assert.deepEqual(actual,owner);await unlink(owner.path);}
  assert.equal(await readFile(foreign,'utf8'),'do not delete');ok(await f.call(r));assert.equal((await f.raw()).events.filter(e=>e.type==='review').length,1,phase);assert.equal((await f.call(r)).replayed,true);
 }
});

test('R-E three busy deferrals do not loop at before_final; dependency and actual input reconciliation release only on meaningful change',async t=>{
 const f=await fixture(t);await f.enable();await f.post(1);let c;
 for(let n=0;n<3;n++){c=await f.claim(await f.cp());ok(await f.resolve(c,'defer',{defer:{kind:'busy',trigger:'step_complete',evidence_ref:'actual current step boundary'}}));assert.equal((await f.cp({trigger:'before_final'})).items.length,0);}
 c=await f.claim(await f.cp());assert.equal((await f.resolve(c,'defer',{defer:{kind:'busy',trigger:'step_complete',evidence_ref:'again'}})).reasonCode,'DEFER_LIMIT');ok(await f.resolve(c,'defer',{defer:{kind:'dependency',trigger:'dependency_change',evidence_ref:'wait task2 submit',condition:{task_id:'t2',status:'submitted'}}}));assert.equal((await f.cp()).items.length,0);await f.event('submit',{taskId:'t2',summary:'dependency progressed'},'w2');c=await f.claim(await f.cp());ok(await f.resolve(c,'defer',{defer:{kind:'needs-input',trigger:'resume',evidence_ref:'actual missing choice'}}));const cp=await f.cp(),l=await f.ledger();assert.ok(cp.heldItems.some(i=>i.itemId===c.claim.itemId));ok(await f.call(f.req('resolve',{run_id:'run',generation:l.consumer.generation,expected_control_revision:l.controlRevision,expected_work_id:l.activeWorkId,item_id:c.claim.itemId,checkpoint_id:cp.checkpointId,disposition:'reconcile',reason_ref:'actual user response',human_ref:'current human input'})));assert.ok((await f.cp()).items.some(i=>i.itemId===c.claim.itemId));
});

test('R-G legacy approval between durable business write and projection does not block exact review receipt recovery',async t=>{
 const f=await fixture(t,{submitted:true});await f.enable();const c=await f.claim(await f.cp()),r=f.req('start_review',{run_id:'run',generation:c.claim.generation,claim_id:c.claim.id,expected_state_version:(await f.raw()).version});const failed=await f.call(r,{fault:phase=>{if(phase==='after-business')throw Object.assign(new Error('isolated crash'),{code:'EIO'});}});assert.equal(failed.reasonCode,'STORAGE_ERROR');await f.event('approve',{summary:'legacy writer actual independent acceptance',evidence:['fixture']});ok(await f.call(r));assert.equal((await f.raw()).tasks[0].status,'approved');assert.equal((await f.raw()).events.filter(e=>e.type==='review').length,1);assert.equal((await f.call(r)).replayed,true);
});

test('wrapped escaped checkpoint and original operation status stay below actual MCP64KiB before commit',async t=>{
 const f=await fixture(t);await f.enable();for(let n=1;n<=3;n++)ok(await f.post(n,{kind:'stage',summary:'\\'.repeat(1800),evidence:Array.from({length:8},()=>({kind:'artifact',ref:'\\'.repeat(500)}))}));const cp=await f.cp({limit:8});const wire=v=>Buffer.byteLength(JSON.stringify({content:[{type:'text',text:JSON.stringify(v)}],isError:false}));assert.ok(cp.items.length<3);assert.equal(cp.hasMore,true);assert.ok(wire(cp)<65536);const recovered=ok(await f.call(f.req('status',{operation_id:cp.checkpointId})));assert.ok(wire(recovered)<65536);assert.deepEqual(recovered.operation.response,cp);
});

test('capacity512 real accepted messages refuses the next without dropping pending audit or returning success',async t=>{
 const f=await fixture(t);await f.enable();for(let n=0;n<512;n++)ok(await f.post(n,{kind:'stage'}));const before=await readFile(f.statePath+'.manager-inbox.json','utf8');assert.equal((await f.post(512,{kind:'stage'})).reasonCode,'INBOX_CAPACITY');assert.equal(await readFile(f.statePath+'.manager-inbox.json','utf8'),before);assert.equal((await f.ledger()).items.filter(i=>i.state==='queued').length,512);
});

test('R-A canonical missing post recovers at checkpoint without replacing current discussion; full review→approve closes formal only',async t=>{
 const f=await fixture(t);await f.enable();await f.cp({continuation:userWork(),transition:'save',expected_work_id:null});await f.event('submit',{summary:'Formal while discussing'},'w');const snapshot=await f.cp();assert.equal(snapshot.activeWork.work_id,'discussion');assert.equal((await f.raw()).tasks[0].status,'submitted');const c=await f.claim(snapshot);assert.equal(c.claim.resumeRef,'discussion');
 const review=ok(await f.call(f.req('start_review',{run_id:'run',generation:c.claim.generation,claim_id:c.claim.id,expected_state_version:(await f.raw()).version})));assert.equal((await f.raw()).tasks[0].status,'reviewing');assert.equal((await f.resolve(c,'settle',{decision_event_id:review.businessEventId})).reasonCode,'REVIEW_NOT_FINISHED');
 const approved=await f.event('approve',{summary:'independent actual decision',evidence:['fixture']});ok(await f.resolve(c,'settle',{decision_event_id:approved.id}));assert.equal((await f.ledger()).activeWorkId,'discussion');
});
test('R-B same run compaction retains exact review focus despite a real old approved task, unknown effect cannot reset',async t=>{
 const f=await fixture(t,{submitted:true});await f.event('submit',{taskId:'t2',summary:'Old cover already complete'},'w2');await f.event('review',{taskId:'t2'});await f.event('approve',{taskId:'t2',summary:'Old verified cover',evidence:['fixture']});await f.enable();const cp=await f.cp(),c=await f.claim(cp);ok(await f.call(f.req('start_review',{run_id:'run',generation:c.claim.generation,claim_id:c.claim.id,expected_state_version:(await f.raw()).version})));const before=await f.ledger();const resumed=await f.cp({trigger:'post_compaction'});assert.equal(resumed.activeWork.task_ref.submit_event_id,'submit-1');assert.equal(resumed.consumer.generation,before.consumer.generation);assert.equal((await f.raw()).tasks[1].status,'approved');
 const old=before.works.find(w=>w.work_id===before.activeWorkId),clean={...old};for(const k of ['owner_binding','observed_state_version','recovery_generation'])delete clean[k];clean.last_effect={operation_ref:'bounded-check',status:'started',evidence_ref:null};ok(await f.cp({continuation:clean,transition:'save',expected_work_id:old.work_id}));const l=await f.ledger();const reset=await f.call(f.req('checkpoint',{run_id:'run',expected_control_revision:l.controlRevision,trigger:'resume',expected_work_id:l.activeWorkId,transition:'save',continuation:{...clean,continuation_revision:clean.continuation_revision+1,last_effect:{operation_ref:null,status:'not-started',evidence_ref:null}}}));assert.equal(reset.reasonCode,'EFFECT_RECONCILIATION_REQUIRED');assert.equal((await f.ctl('pause_claims')).claimsPaused,true);
 const release=await f.call(f.req('control',{command:'release_consumer',authorization_ref:'fixture',run_id:'run',generation:l.consumer.generation,expected_work_id:l.activeWorkId,expected_control_revision:(await f.ledger()).controlRevision}));assert.equal(release.reasonCode,'UNRESOLVED_EFFECT');
});
test('R-C exact operation/message replay and status, changed step cannot evade identity, resubmit supersedes old canonical entry',async t=>{
 const f=await fixture(t);await f.enable();const r=f.req('post',{message:{kind:'progress',message_id:'stable',round_id:'r',task_id:'t',step_id:'one',producer_seq:1,summary:'report',evidence:[]}},'w'),first=ok(await f.call(r)),again=ok(await f.call(r));assert.deepEqual({...again,replayed:undefined},{...first,replayed:undefined});const observed=ok(await f.call(f.req('status',{operation_id:r.operation_id},'w')));assert.equal(observed.operation.response.inboxVersion,first.inboxVersion);
 assert.equal((await f.call({...r,operation_id:'changed-step',message:{...r.message,step_id:'other'}})).reasonCode,'MESSAGE_CONFLICT');assert.equal((await f.call({...r,message:{...r.message,summary:'other'}})).reasonCode,'OPERATION_CONFLICT');
 await f.event('submit',{summary:'v1'},'w');await f.cp();await f.event('review');await f.event('rework',{summary:'change'});await f.event('submit',{summary:'v2'},'w');await f.cp();const items=(await f.ledger()).items.filter(i=>i.kind==='submission');assert.equal(items.length,2);assert.equal(items[0].state,'superseded');
});
test('R-D freeze claim/ack retains later progress without changing audit; no-claim settle rejects and split retry finds exact seq',async t=>{
 const f=await fixture(t);await f.enable();const p1=ok(await f.post(1)),cp=await f.cp(),p2=ok(await f.post(2)),auditBefore=(await f.ledger()).audit;const l=await f.ledger(),bare={run_id:'run',generation:l.consumer.generation,expected_control_revision:l.controlRevision,expected_work_id:null,item_id:p1.itemId,checkpoint_id:cp.checkpointId,reason_ref:'read old only'};
 assert.equal((await f.call(f.req('resolve',{...bare,disposition:'settle'}))).reasonCode,'CLAIM_REQUIRED');ok(await f.call(f.req('resolve',{...bare,disposition:'acknowledge'})));const after=await f.ledger();assert.deepEqual(after.audit.slice(0,auditBefore.length),auditBefore);assert.equal(after.items.find(i=>i.id===p1.itemId).received.payloadSeq,p1.arrivalSeq);assert.ok(after.items.some(i=>i.state==='queued'&&i.pendingSeqs.includes(p2.arrivalSeq)));const repeated=ok(await f.post(2));assert.equal(repeated.arrivalSeq,p2.arrivalSeq);
 const c=await f.claim(await f.cp());ok(await f.resolve(c,'settle'));assert.ok((await f.ledger()).items.some(i=>i.state==='queued'&&i.pendingSeqs.includes(p2.arrivalSeq)));
});
test('R-F simultaneous different item claims, compaction, TTL-independent busy, recovery new generation and old instance fence',async t=>{
 const f=await fixture(t);await f.enable();await f.post(1);await f.post(1,{},'w2');const cp=await f.cp(),l=await f.ledger();const request=i=>f.req('claim',{run_id:'run',generation:l.consumer.generation,expected_control_revision:l.controlRevision,expected_work_id:null,checkpoint_id:cp.checkpointId,item_id:cp.items[i].itemId,payload_seq:cp.items[i].payloadSeq,boundary_ref:'fixture boundary'});
 const requests=[request(0),request(1)],result=await Promise.all(requests.map(r=>f.call(r)));assert.ok(result.filter(r=>r.status==='claimed').length<=1);if(!result.some(r=>r.status==='claimed'))ok(await f.call(requests[0]));const c=await f.ledger();assert.equal(c.claims.filter(x=>x.phase==='active').length,1);assert.notEqual((await f.call(request(1),{at:'2027-01-01T00:00:00.000Z'})).status,'claimed');await f.ctl('pause_claims');
 const rec={old_run_id:'run',old_generation:c.consumer.generation,old_execution_ended:true,quiescence_ref:'verified isolated ended instance',effects:[],no_effect_intents:[]},args={command:'recover',authorization_ref:'authorized recovery',expected_control_revision:(await f.ledger()).controlRevision,run_id:'run',generation:c.consumer.generation,expected_work_id:c.activeWorkId,claim_id:c.consumer.claimId,recovery:rec};assert.equal((await f.call(f.req('control',args))).reasonCode,'NEW_INSTANCE_REQUIRED');ok(await f.call(f.req('control',{...args,run_id:'new-run'})));assert.equal((await f.call(f.req('checkpoint',{run_id:'run',expected_control_revision:(await f.ledger()).controlRevision,trigger:'resume'}))).reasonCode,'CONSUMER_BUSY');
});
test('R-G all start_review intent/business/projection fault boundaries recover exact operation without duplicate review',async t=>{
 for(const phase of ['before-review-intent','after-review-intent','before-business','after-business','before-review-projection','after-review-projection']){
  const f=await fixture(t,{submitted:true});await f.enable();const c=await f.claim(await f.cp()),r=f.req('start_review',{run_id:'run',generation:c.claim.generation,claim_id:c.claim.id,expected_state_version:(await f.raw()).version});let thrown=false;const failed=await f.call(r,{fault:where=>{if(where===phase&&!thrown){thrown=true;throw Object.assign(new Error('isolated disk/crash boundary'),{code:'EIO'});}}});assert.equal(failed.reasonCode,'STORAGE_ERROR',phase);ok(await f.call(r));assert.equal((await f.raw()).events.filter(e=>e.type==='review').length,1,phase);assert.equal((await f.call(r)).replayed,true);
 }
});
test('R-H observe no consumer/business effect, roles/CAS/mode/unknown-effect controls do not silently change defaults',async t=>{
 const f=await fixture(t,{submitted:true}),before=await readFile(f.statePath,'utf8');const cp=await f.cp();assert.equal(cp.status,'shadow-checkpoint');assert.equal(cp.consumer,null);assert.equal(await readFile(f.statePath,'utf8'),before);assert.equal((await f.call(f.req('claim',{run_id:'run',generation:0,expected_control_revision:1,expected_work_id:null,checkpoint_id:cp.checkpointId,item_id:cp.items[0].itemId,payload_seq:cp.items[0].payloadSeq,boundary_ref:'fixture'}))).reasonCode,'MODE_NOT_CONSUMING');
 assert.equal((await f.call(f.req('control',{command:'pause_claims',authorization_ref:'no worker authority',expected_control_revision:1},'w'))).reasonCode,'ROLE_DENIED');await f.enable();await f.claim(await f.cp());assert.equal((await f.call(f.req('control',{command:'set_mode',authorization_ref:'fixture',expected_control_revision:(await f.ledger()).controlRevision,mode:'legacy'}))).reasonCode,'UNRESOLVED_EFFECT');
 assert.equal((await f.call(f.req('checkpoint',{run_id:'run',expected_control_revision:0,trigger:'resume'}))).reasonCode,'CONTROL_VERSION_CONFLICT');
});
test('strict core raw duplicate/depth/Unicode/unknown fields, wrong task and corruption are nonmutating; real disk failure has no fallback sender',async t=>{
 const f=await fixture(t);await f.enable();const before=await readFile(f.statePath+'.manager-inbox.json','utf8');for(const raw of ['{"action":"status","action":"post"}',JSON.stringify({x:Array.from({length:100},()=>1),deep:JSON.parse('['.repeat(40)+'0'+']'.repeat(40))})])assert.equal((await f.call(raw)).status,'error');
 assert.throws(()=>validateInboxRequest({action:'status',actor_host_id:'h',actor_thread_id:'t',team_id:'team',reason:'manual',path:'C:/private'}));assert.throws(()=>validateInboxRequest({action:'status',actor_host_id:'h',actor_thread_id:'t',team_id:'team',reason:'manual',item_id:'\ud800'}));
 const denied=await f.post(1,{task_id:'t2'});assert.equal(denied.reasonCode,'TASK_SCOPE_CONFLICT');assert.equal(await readFile(f.statePath+'.manager-inbox.json','utf8'),before);let sends=0;const failure=await f.call(f.req('post',{message:{kind:'stage',message_id:'disk-failure',round_id:'r',task_id:'t',step_id:'step',producer_seq:1,summary:'report',evidence:[]}},'w'),{write:async()=>{throw Object.assign(new Error('full disk'),{code:'ENOSPC'});},nativeSend:()=>{sends++;}});assert.equal(failure.reasonCode,'STORAGE_ERROR');assert.equal(sends,0);assert.equal(await readFile(f.statePath+'.manager-inbox.json','utf8'),before);
 await writeFile(f.statePath+'.manager-inbox.json','{"schemaVersion":"corrupt"}');assert.equal((await f.call(f.req('status'))).status,'error');
});
test('historical submit tuple never loans new binding or unknown revision; transport unknown→accepted releases from actual E03 ledger only',async t=>{
 const f=await fixture(t,{submitted:true});await f.enable();const synthetic=await f.raw();synthetic.team.source.kind='manual';synthetic.events.forEach(e=>e.source.kind='manual');await writeFile(f.statePath,JSON.stringify(synthetic));const noticeReq={action:'prepare',actor_host_id:'fixture-host',actor_thread_id:'fixture-w',team_id:'team',task_id:'t',submission_id:'submit-1',reason:'manual',operation_id:'e03-prepare',baseline:{outcome:'not-attempted',evidence:{kind:'observation',ref:'fixture',detail:'no native send; isolated'}}},n=ok(await noticeRuntime({statePath:f.statePath,registryPath:f.registryPath,request:noticeReq,options:f.options}));assert.equal(n.sendNow,true);const held=await f.cp();assert.equal(held.items.length,0);let l=await f.ledger();assert.equal(l.items[0].state,'transport-hold');assert.equal(ok(await f.call(f.req('status'))).items[0].payload.summary,null);
 const {baseline,...fields}=noticeReq;ok(await noticeRuntime({statePath:f.statePath,registryPath:f.registryPath,request:{...fields,action:'result',operation_id:'e03-result',attempt_id:n.attemptId,result:{outcome:'accepted',evidence:{kind:'host-result',ref:'synthetic exact terminal result',detail:'fixture only'}}},options:f.options}));assert.equal((await f.cp()).items[0].state,'queued');
 const newer=f.native.teams[0].members.find(m=>m.id==='w');newer.binding.threadId='replacement';newer.binding.revision=2;f.native.teams[0].revision=2;await writeFile(f.registryPath,JSON.stringify(f.native));let state=await f.raw();state.members.find(m=>m.id==='w').binding.threadId='replacement';state.registry.teamRevision=2;await writeFile(f.statePath,JSON.stringify(state));await f.cp();l=await f.ledger();assert.equal(l.items[0].state,'identity-hold');assert.equal(l.items[0].sender.threadId,'fixture-w');
});
