import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,appendFile,rename,symlink,link,rm,realpath,mkdir,cp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,sep,basename} from 'node:path';
import {createHash} from 'node:crypto';
import {demoState} from '../src/demo.mjs';
import {evolve} from '../src/runtime.mjs';
import {planSources,applySources,writeSourcePlan} from '../src/source-onboarding.mjs';
import {refreshStats,releaseStatsSession,readStatsIndex} from '../src/stats-collector.mjs';
import {queryStats,querySourceStatus,createStatsSnapshot} from '../src/stats-query.mjs';
import {recordActivity} from '../src/stats-activity.mjs';
import {sourceStatusMarkup,sourceStatusFacts} from '../src/dashboard-v2-client.mjs';
import {startDashboardServer} from '../src/dashboard-live.mjs';
import {run} from '../src/cli.mjs';
const at=n=>new Date(Date.UTC(2026,9,6,0,n)).toISOString(),lines=x=>x.map(v=>JSON.stringify(v)).join('\n')+'\n';
const usage=(n,when=at(n))=>({type:'event_msg',timestamp:when,payload:{type:'token_count',info:{last_token_usage:{input_tokens:n*10,cached_input_tokens:n*4,output_tokens:n*2,reasoning_output_tokens:n,total_tokens:n*99},total_token_usage:{input_tokens:n*10,cached_input_tokens:n*4,output_tokens:n*2,reasoning_output_tokens:n,total_tokens:n*99}}}});
async function fixture(t){
  const root=await mkdtemp(join(tmpdir(),'runtime-source-onboarding-')),state=demoState(),statePath=join(root,'state.json'),manifestPath=join(root,'manifest.json'),cache=join(root,'cache'),path=join(root,'explicit.jsonl'),member=state.members.find(m=>m.id==='worker-04');
  const common={authorizedFrom:'2026-09-01T00:00:00.000Z',authorizedTo:at(60),adapterVersion:'v1',coverageAssertions:{status:'partial',evidenceRef:'fixture:partial'},evidenceRef:'fixture:source',bindings:[],selection:{taskId:null,roundId:null,turnIds:[],itemIds:[]}};
  const manifest={schemaVersion:'dashboard-sources/v1',teamId:state.team.id,registryId:'fixture-registry',revision:1,authorizationRef:'fixture:approved-manifest',sources:[{...common,sourceId:'state',kind:'recorded-state',path:statePath,mutationPolicy:'mutable'}]};
  await writeFile(statePath,JSON.stringify(state));await writeFile(manifestPath,JSON.stringify(manifest));await writeFile(path,lines([{type:'session_meta',payload:{id:member.binding.threadId,privatePrompt:'not metadata; never in plan or HTTP'}}]));
  const request={authorizationRef:'fixture:explicit-user-candidate-grant',candidates:[{mode:'codex-jsonl',path,memberId:member.id,authorizedTo:at(60),from:'now'}]},plan=()=>planSources(statePath,manifestPath,request,{now:()=>at(0)}),refresh=()=>refreshStats(manifestPath,cache,{asOf:at(5)}),audit=(input={},baseSnapshotId)=>querySourceStatus(cache,state.members,input,{baseSnapshotId,now:Date.parse(at(5))});
  t.after(async()=>{releaseStatsSession(cache);const target=await realpath(root),parent=await realpath(tmpdir());assert.ok(target.startsWith(parent+sep)&&/^runtime-source-onboarding-/.test(basename(target)));if(process.env.SOURCE_ONBOARDING_TEST_EVIDENCE){const dest=join(process.env.SOURCE_ONBOARDING_TEST_EVIDENCE,createHash('sha256').update(t.name).digest('hex').slice(0,12));await mkdir(process.env.SOURCE_ONBOARDING_TEST_EVIDENCE,{recursive:true});await cp(target,dest,{recursive:true,errorOnExist:true,force:false});await writeFile(join(dest,'case.json'),JSON.stringify({kind:'synthetic, not production',name:t.name,originalTemporaryRoot:root,rerun:'node --test test/source-onboarding.test.mjs'},null,2));}await rm(target,{recursive:true,force:true,maxRetries:3});});
  return {root,state,statePath,manifestPath,cache,path,member,manifest,request,plan,refresh,audit,common};
}
test('new/current member has specific unconfigured facts; actual CLI plan/apply adds authorized exact candidate without historical backfill',async t=>{
  const f=await fixture(t);await f.refresh();let status=(await f.audit()).rows.find(r=>r.memberId===f.member.id);assert.equal(status.metrics.token.configuration,'not-configured');assert.equal(status.metrics.token.observedRecords,0);
  const requestPath=join(f.root,'request.json'),planPath=join(f.root,'plan.json');await writeFile(requestPath,JSON.stringify({...f.request,candidates:[{...f.request.candidates[0],authorizedTo:'2100-01-01T00:00:00.000Z'}]}));
  // Exercise CLI arguments and exclusive plan output with an explicit future
  // finite range, using the real current clock for this one synthetic CLI case.
  const future=new Date(Date.now()+3600000).toISOString();await writeFile(requestPath,JSON.stringify({...f.request,candidates:[{...f.request.candidates[0],authorizedTo:future}]}));const out=[];await run(['stats-source-plan',f.statePath,f.manifestPath,requestPath,planPath],v=>out.push(JSON.parse(v)));await run(['stats-source-apply',f.statePath,f.manifestPath,planPath],v=>out.push(JSON.parse(v)));assert.equal(out[1].added,1);assert.equal(JSON.stringify(JSON.parse(await readFile(planPath))).includes('not metadata'),false);
  const next=JSON.parse(await readFile(f.manifestPath));assert.deepEqual(next.sources[0],f.manifest.sources[0]);assert.ok(next.sources[1].authorizedFrom>=f.state.updatedAt);
});
test('exact candidate becomes configured/no-records, append becomes observed; repeat plan retains full approved descriptor and cannot widen window',async t=>{
  const f=await fixture(t),plan=await f.plan();await applySources(f.statePath,f.manifestPath,plan);await f.refresh();let row=(await f.audit()).rows.find(r=>r.memberId===f.member.id);assert.equal(row.metrics.token.configuration,'configured');assert.equal(row.metrics.token.collection,'no-records');
  await appendFile(f.path,lines([usage(1,at(-1)),usage(2,at(1))]));await f.refresh();row=(await f.audit()).rows.find(r=>r.memberId===f.member.id);assert.equal(row.metrics.token.collection,'observed');assert.equal(row.metrics.token.observedRecords,1);const token=await queryStats(f.cache,{view:'token',preset:'all'},{now:Date.parse(at(5))});assert.equal(token.data.summary.token.nativeTotal.total.known,198);
  const before=await readFile(f.manifestPath),repeat=await planSources(f.statePath,f.manifestPath,f.request,{now:()=>at(2)});assert.deepEqual(repeat.after,plan.after);assert.equal((await applySources(f.statePath,f.manifestPath,repeat)).status,'unchanged');assert.deepEqual(await readFile(f.manifestPath),before);
  if(process.platform==='win32'){const caseAlias=await planSources(f.statePath,f.manifestPath,{...f.request,candidates:[{...f.request.candidates[0],path:f.path.toUpperCase()}]},{now:()=>at(2)});assert.deepEqual(caseAlias.after,plan.after);}
  const hardAlias=join(f.root,'hard-alias.jsonl');await link(f.path,hardAlias);await assert.rejects(planSources(f.statePath,f.manifestPath,{...f.request,candidates:[{...f.request.candidates[0],path:hardAlias}]},{now:()=>at(2)}),/descriptor_conflict/);
  await assert.rejects(planSources(f.statePath,f.manifestPath,{...f.request,candidates:[{...f.request.candidates[0],authorizedTo:at(120)}]},{now:()=>at(2)}),/descriptor_conflict/);
});
test('wrong thread/team, unknown/header limit, past authorization and candidate symlink refuse before mutation',async t=>{
  const f=await fixture(t),before=await readFile(f.manifestPath);await writeFile(f.path,lines([{type:'session_meta',payload:{id:'other'}}]));await assert.rejects(f.plan(),/identity_mismatch/);
  await writeFile(f.path,lines([{type:'session_meta',teamId:'other',payload:{id:f.member.binding.threadId}}]));await assert.rejects(f.plan(),/team_mismatch/);
  await writeFile(f.path,'x'.repeat(65537));await assert.rejects(f.plan(),/header_unavailable/);await writeFile(f.path,lines([{type:'session_meta',payload:{id:f.member.binding.threadId}}]));
  await assert.rejects(planSources(f.statePath,f.manifestPath,{...f.request,candidates:[{...f.request.candidates[0],from:at(-1)}]},{now:()=>at(0)}),/historical_authorization_refused/);
  const alias=join(f.root,'alias.jsonl');try{await symlink(f.path,alias,'file');await assert.rejects(planSources(f.statePath,f.manifestPath,{...f.request,candidates:[{...f.request.candidates[0],path:alias}]},{now:()=>at(0)}),/not_regular/);}catch(e){if(e.code!=='EPERM')throw e;}
  assert.deepEqual(await readFile(f.manifestPath),before);
});
test('concurrent/stale apply is explicit; replay does not append or duplicate, changed state/descriptor rejects',async t=>{
  const f=await fixture(t),plan=await f.plan(),results=await Promise.allSettled([applySources(f.statePath,f.manifestPath,plan),applySources(f.statePath,f.manifestPath,plan)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.ok(results.some(r=>r.status==='rejected'&&r.reason.code==='EEXIST'));assert.equal((await applySources(f.statePath,f.manifestPath,plan)).status,'unchanged');
  const stale=await f.plan(),changed=JSON.parse(await readFile(f.manifestPath));changed.authorizationRef='fixture:changed-original';await writeFile(f.manifestPath,JSON.stringify(changed));await assert.rejects(applySources(f.statePath,f.manifestPath,stale),/stale_manifest/);
  await writeFile(f.manifestPath,JSON.stringify(stale.after));const s=evolve(f.state,{id:'changed-state',type:'block',actor:'manager',at:at(1),source:{kind:'fixture',ref:'state-change'},taskId:'T-4',roundId:'round-demo',summary:'Synthetic scope change'},f.state.version);await writeFile(f.statePath,JSON.stringify(s));await assert.rejects(applySources(f.statePath,f.manifestPath,stale),/stale_state/);
});
test('approved descriptor keeps exact historic epochs and no-op; output protects state lock and explicit grant',async t=>{
  const f=await fixture(t),first=await f.plan(),grantPath=join(f.root,'grant.json');await writeFile(grantPath,JSON.stringify(first.after));const request={authorizationRef:'fixture:explicit-verified-original-grant',candidates:[{mode:'approved-source',grantManifest:grantPath,sourceId:first.after.sources[1].sourceId}]};
  const plan=await planSources(f.statePath,f.manifestPath,request,{now:()=>at(2)});assert.deepEqual(plan.after.sources[1],first.after.sources[1]);await applySources(f.statePath,f.manifestPath,plan);const repeat=await planSources(f.statePath,f.manifestPath,request,{now:()=>at(3)});assert.equal(repeat.after.revision,plan.after.revision);
  for(const path of [f.statePath+'.lock',(await realpath(f.statePath))+'.lock',grantPath,f.manifestPath+'.sources.lock'])await assert.rejects(writeSourcePlan(path,plan),/path_collision/);
  const bad=JSON.parse(await readFile(grantPath));bad.teamId='wrong-team';await writeFile(grantPath,JSON.stringify(bad));await assert.rejects(planSources(f.statePath,f.manifestPath,request,{now:()=>at(3)}),/team_mismatch/);
});
test('configured empty vs read error vs last-good observed facts; same-path rotation replaces generation, old snapshots do not borrow new scopes',async t=>{
  const f=await fixture(t),plan=await f.plan();await applySources(f.statePath,f.manifestPath,plan);await f.refresh();let row=(await f.audit()).rows.find(r=>r.memberId===f.member.id);assert.equal(row.metrics.token.collection,'no-records');assert.ok(!row.metrics.token.problems.includes('read-error'));
  await appendFile(f.path,lines([usage(1,at(1))]));await f.refresh();const snapshot=await createStatsSnapshot(f.cache,{now:Date.parse(at(5))});await rename(f.path,f.path+'.old');await writeFile(f.path,lines([{type:'session_meta',payload:{id:f.member.binding.threadId}},usage(3,at(2))]));await f.refresh();const q=await queryStats(f.cache,{view:'token',preset:'all'},{now:Date.parse(at(5))});assert.equal(q.data.summary.token.nativeTotal.total.known,297);
  await rm(f.path);await f.refresh();row=(await f.audit()).rows.find(r=>r.memberId===f.member.id);assert.equal(row.metrics.token.collection,'observed');assert.ok(row.metrics.token.problems.includes('read-error'));assert.ok(row.metrics.token.problems.includes('continuity-unproven'));assert.equal(row.metrics.token.observedRecords,1);
  const old=await f.audit({},snapshot.baseSnapshotId);assert.ok(!old.rows.find(r=>r.memberId===f.member.id).metrics.token.problems.includes('read-error'));
  const indexPath=join(f.cache,'stats-index.json'),index=await readStatsIndex(f.cache);delete index.sourceScopes;await writeFile(indexPath,JSON.stringify(index));const legacy=await createStatsSnapshot(f.cache,{now:Date.parse(at(5))+1});assert.equal((await f.audit({},legacy.baseSnapshotId)).rows.find(r=>r.memberId===f.member.id).metrics.token.configuration,'unverified');
  await f.refresh();assert.equal((await f.audit({},legacy.baseSnapshotId)).rows.find(r=>r.memberId===f.member.id).metrics.token.configuration,'unverified');
});
test('cross-window complete interval is observed by the same intersection rule; missing-end and historical identity stay separate',async t=>{
  const f=await fixture(t),b={memberId:f.member.id,hostId:f.member.binding.hostId,threadId:f.member.binding.threadId,role:'Worker',bindingRevision:1,roleEpoch:'explicit-historical',from:'2026-09-01T00:00:00.000Z',to:'2026-11-01T00:00:00.000Z',evidenceRef:'fixture:interval-binding'},activityPath=join(f.root,'activity.jsonl'),source={...f.common,sourceId:'activity',kind:'activity-jsonl',path:activityPath,mutationPolicy:'append-only',authorizedTo:b.to,bindings:[b],selection:{taskId:'T-4',roundId:'round-demo',turnIds:[],itemIds:[]}};f.manifest.sources.push(source);await writeFile(f.manifestPath,JSON.stringify(f.manifest));
  const event={schemaVersion:'activity-sidecar/v1',eventId:'cross',phase:'begin',teamId:f.state.team.id,memberId:b.memberId,hostId:b.hostId,threadId:b.threadId,role:b.role,bindingRevision:b.bindingRevision,roleEpoch:b.roleEpoch,taskId:'T-4',roundId:'round-demo',stepId:'cross-day',at:'2026-10-03T00:00:00.000Z',assurance:'worker-declared',sourceKind:'activity-sidecar',evidenceRef:'fixture:cross'};await recordActivity(f.manifestPath,'activity',event);await recordActivity(f.manifestPath,'activity',{...event,phase:'end',at:'2026-10-05T00:00:00.000Z'});await recordActivity(f.manifestPath,'activity',{...event,eventId:'missing',stepId:'missing',at:'2026-10-03T00:00:00.000Z'});await f.refresh();const window={preset:'custom',from:'2026-10-04',to:'2026-10-04'},audit=await f.audit(window),q=await queryStats(f.cache,{view:'steps',...window},{now:Date.parse(at(5))});assert.equal(q.data.total,1);assert.equal(audit.rows.find(r=>r.memberId===f.member.id).metrics.time.observedRecords,1);
  const other=structuredClone(f.state.members);other.find(m=>m.id===f.member.id).binding.threadId='new-binding';const health=await querySourceStatus(f.cache,other,window,{now:Date.parse(at(5))});assert.equal(health.rows.find(r=>r.memberId===f.member.id).metrics.time.configuration,'not-configured');assert.equal(health.rows.find(r=>r.memberId===f.member.id).metrics.time.observedRecords,0);
});
test('actual Dashboard carries specific read-only facts and escapes detail without paths/commands/private header',async t=>{
  const f=await fixture(t);await applySources(f.statePath,f.manifestPath,await f.plan());await f.refresh();const service=await startDashboardServer({statePath:f.statePath,teamId:f.state.team.id,sourceManifestPath:f.manifestPath,statsCachePath:f.cache,port:0,now:()=>Date.parse(at(5))});t.after(()=>service.close());const token=new URLSearchParams(new URL(service.url).hash.slice(1)).get('token'),response=await fetch(service.origin+'/api/v2/overview?preset=all',{headers:{Authorization:'Bearer '+token}});assert.equal(response.status,200);const data=await response.json(),metrics=data.data.currentSourceStatus.find(r=>r.memberId===f.member.id).metrics;assert.equal(metrics.token.configuration,'configured');assert.equal(metrics.token.collection,'no-records');const wire=JSON.stringify(data);assert.ok(!wire.includes(f.root)&&!wire.includes('privatePrompt'));const html=sourceStatusMarkup(metrics,'token',f.member.id);assert.match(html,/已配置·无记录/);assert.ok(html.includes('data-source-member="'+f.member.id+'"'));assert.match(html,/aria-haspopup="dialog"/);const facts=sourceStatusFacts(metrics,'token');assert.match(facts,/来源证据/);assert.doesNotMatch(facts,/执行命令|privatePrompt/);
});
