import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,mkdir,rm,realpath} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,sep,basename} from 'node:path';
import {beginActivity,endActivity} from '../src/stats-activity.mjs';
import {refreshStats,releaseStatsSession} from '../src/stats-collector.mjs';
import {queryStats} from '../src/stats-query.mjs';
import {run} from '../src/cli.mjs';
import {declaredActivityText} from '../src/dashboard-v2-client.mjs';
const at='2026-10-06T00:00:00.000Z',end='2026-10-06T00:00:01.500Z',asOf='2026-10-06T00:01:00.000Z';
async function fixture(t,{missingParent=false}={}){const root=await mkdtemp(join(tmpdir(),'runtime-activity-producer-')),cache=join(root,'cache'),path=join(root,...(missingParent?['later']:[]),'activity.jsonl'),manifestPath=join(root,'manifest.json'),receipt=join(root,'receipt.json');t.after(async()=>{releaseStatsSession(cache);const target=await realpath(root),parent=await realpath(tmpdir());assert.ok(target.startsWith(parent+sep)&&/^runtime-activity-producer-/.test(basename(target)));await rm(target,{recursive:true,force:true,maxRetries:3});});
  const binding={memberId:'worker',hostId:'local',threadId:'thread',bindingRevision:1,role:'Worker',roleEpoch:'epoch',from:'2026-10-01T00:00:00.000Z',to:'2026-11-01T00:00:00.000Z',evidenceRef:'fixture:identity'},source={sourceId:'activity',kind:'activity-jsonl',path,adapterVersion:'v1',mutationPolicy:'append-only',authorizedFrom:binding.from,authorizedTo:binding.to,coverageAssertions:{status:'partial',evidenceRef:'fixture:coverage'},evidenceRef:'fixture:authorized-producer',bindings:[binding],selection:{taskId:'task',roundId:'round',turnIds:[],itemIds:[]}},manifest={schemaVersion:'dashboard-sources/v1',teamId:'team',registryId:'registry',revision:1,authorizationRef:'fixture:authorized',sources:[source]},context={teamId:'team',memberId:'worker',hostId:'local',threadId:'thread',bindingRevision:1,roleEpoch:'epoch',role:'Worker',taskId:'task',roundId:'round',stepId:'implement',assurance:'worker-declared',evidenceRef:'fixture:actual-begin-end'};await writeFile(manifestPath,JSON.stringify(manifest));return {root,cache,path,manifestPath,manifest,receipt,context};}
test('actual begin/end producer writes a stable receipt, preserves owner evidence, and collector/query keep declaration apart from machine MCP',async t=>{const f=await fixture(t),first=await beginActivity(f.manifestPath,'activity',f.context,f.receipt,{now:()=>at});await beginActivity(f.manifestPath,'activity',f.context,f.receipt,{now:()=>end});await refreshStats(f.manifestPath,f.cache,{asOf});const pending=await queryStats(f.cache,{view:'steps',taskId:'task',memberId:'worker'});assert.equal(pending.data.rows[0].durationMs,null);await endActivity(f.manifestPath,f.receipt,{now:()=>end});await endActivity(f.manifestPath,f.receipt,{now:()=>asOf});const entries=(await readFile(f.path,'utf8')).trim().split('\n').map(JSON.parse);assert.equal(entries.length,2);assert.equal(entries[0].eventId,first.eventId);assert.equal(entries[1].at,end);await refreshStats(f.manifestPath,f.cache,{asOf});const q=await queryStats(f.cache,{view:'steps',taskId:'task',memberId:'worker'}),row=q.data.rows[0];assert.equal(q.data.total,1);assert.equal(row.stepId,'implement');assert.equal(row.memberId,'worker');assert.equal(row.role,'Worker');assert.equal(row.durationMs,1500);assert.equal(row.assurance,'worker-declared');assert.equal(q.data.summary.mcp[0].calls,null);assert.equal(q.data.summary.intervals[0].sourceKind,'activity-sidecar');});
test('invalid/cross-team context cannot append; failed append retries identical intent, and changed source scope refuses end',async t=>{const f=await fixture(t,{missingParent:true});await assert.rejects(beginActivity(f.manifestPath,'activity',{...f.context,teamId:'other'},f.receipt,{now:()=>at}),/team_mismatch/);await assert.rejects(beginActivity(f.manifestPath,'activity',f.context,f.receipt,{now:()=>at}),/ENOENT/);const planned=JSON.parse(await readFile(f.receipt));assert.equal(planned.beginRecorded,false);await mkdir(join(f.root,'later'));await beginActivity(f.manifestPath,'activity',f.context,f.receipt,{now:()=>end});const actual=JSON.parse((await readFile(f.path,'utf8')).trim());assert.equal(actual.eventId,planned.beginEvent.eventId);assert.equal(actual.at,at);await assert.rejects(beginActivity(f.manifestPath,'activity',{...f.context,stepId:'different'},f.receipt,{now:()=>end}),/context_mismatch/);f.manifest.sources[0].selection.taskId='other';await writeFile(f.manifestPath,JSON.stringify(f.manifest));await assert.rejects(endActivity(f.manifestPath,f.receipt,{now:()=>end}),/scope_changed/);assert.equal((await readFile(f.path,'utf8')).trim().split('\n').length,1);});
test('receipt collisions and tampered task/step cannot overwrite manifest or source evidence',async t=>{const f=await fixture(t),original=await readFile(f.manifestPath);for(const receipt of [f.manifestPath,f.path,...(process.platform==='win32'?[f.path.toUpperCase()]:[])]){await assert.rejects(beginActivity(f.manifestPath,'activity',f.context,receipt,{now:()=>at}),/path_collision/);await assert.rejects(endActivity(f.manifestPath,receipt,{now:()=>end}),/path_collision/);}assert.deepEqual(await readFile(f.manifestPath),original);await beginActivity(f.manifestPath,'activity',f.context,f.receipt,{now:()=>at});const bytes=await readFile(f.path),receipt=JSON.parse(await readFile(f.receipt));for(const key of ['taskId','roundId','stepId']){const changed=structuredClone(receipt);changed.beginEvent[key]='forged';await writeFile(f.receipt,JSON.stringify(changed));await assert.rejects(endActivity(f.manifestPath,f.receipt,{now:()=>end}));assert.deepEqual(await readFile(f.path),bytes);}await writeFile(f.receipt,JSON.stringify({...receipt,endEvent:{...receipt.beginEvent,phase:'end',at:end,stepId:'different'}}));await assert.rejects(endActivity(f.manifestPath,f.receipt,{now:()=>end}),/receipt_invalid/);assert.deepEqual(await readFile(f.path),bytes);});
test('actual CLI begin/end commands write and pair the approved step without a business-state operation',async t=>{const f=await fixture(t),contextPath=join(f.root,'context.json'),output=[];await writeFile(contextPath,JSON.stringify(f.context));await run(['stats-activity-begin',f.manifestPath,'activity',contextPath,f.receipt],x=>output.push(JSON.parse(x)));await run(['stats-activity-end',f.manifestPath,f.receipt],x=>output.push(JSON.parse(x)));assert.deepEqual(output.map(x=>x.phase),['begin','end']);const lines=(await readFile(f.path,'utf8')).trim().split('\n').map(JSON.parse);assert.equal(lines.length,2);assert.equal(lines[0].eventId,lines[1].eventId);assert.equal(lines[0].taskId,'task');assert.equal(lines[1].stepId,'implement');});
test('overlapping worker/operator declarations both remain visible as separate intervals without an additive total',async t=>{const f=await fixture(t),operator=join(f.root,'operator-receipt.json');await beginActivity(f.manifestPath,'activity',f.context,f.receipt,{now:()=>at});await beginActivity(f.manifestPath,'activity',{...f.context,assurance:'operator-declared',stepId:'operator-observation'},operator,{now:()=>at});await endActivity(f.manifestPath,f.receipt,{now:()=>end});await endActivity(f.manifestPath,operator,{now:()=> '2026-10-06T00:00:02.000Z'});await refreshStats(f.manifestPath,f.cache,{asOf});const q=await queryStats(f.cache,{view:'members',memberId:'worker'}),summary=q.data.rows[0].time;assert.deepEqual(summary.intervals.map(r=>r.observedUnionMs).toSorted((a,b)=>a-b),[1500,2000]);const text=declaredActivityText(summary);assert.match(text,/Worker声明 1\.50 秒/);assert.match(text,/Operator声明 2\.00 秒/);assert.doesNotMatch(text,/3\.50|3500/);assert.equal(summary.mcp[1].calls,null);});
test('forged completion flag or changed end timestamp cannot acknowledge an unwritten ending',async t=>{const f=await fixture(t);await beginActivity(f.manifestPath,'activity',f.context,f.receipt,{now:()=>at});const original=JSON.parse(await readFile(f.receipt)),before=await readFile(f.path);await writeFile(f.receipt,JSON.stringify({...original,endRecorded:true,endEvent:{...original.beginEvent,phase:'end',at:end}}));await assert.rejects(endActivity(f.manifestPath,f.receipt,{now:()=>end}),/end_evidence_unavailable/);assert.deepEqual(await readFile(f.path),before);await writeFile(f.receipt,JSON.stringify(original));await endActivity(f.manifestPath,f.receipt,{now:()=>end});const closed=JSON.parse(await readFile(f.receipt)),completed=await readFile(f.path);closed.endEvent.at='2026-10-06T00:00:02.000Z';await writeFile(f.receipt,JSON.stringify(closed));await assert.rejects(endActivity(f.manifestPath,f.receipt),/evidence_mismatch/);assert.deepEqual(await readFile(f.path),completed);});
