import {readFile,writeFile,lstat,mkdir} from 'node:fs/promises';
import {resolve,dirname,join,relative,isAbsolute} from 'node:path';
import {readState,atomicWrite} from './store.mjs';
import {withFileLocks} from './registry-projection.mjs';
import {check,exact,id,time,hash,validateManifest} from './stats-contract.mjs';
import {projectDocument} from './stats-adapters.mjs';
import {locateSessions,verifySessionCandidate,localPath} from './session-locator.mjs';
import {refreshStats,readStatsIndex,markStatsBlocked} from './stats-collector.mjs';
import {runActivityStep} from './activity-workflow.mjs';
import {beginActivity,endActivity} from './stats-activity.mjs';
import {validateObservationContext} from './observation-context.mjs';

const POLICY=['schemaVersion','policyId','revision','status','authorizationRef','teamId','hostId','registryPath','statePath','managedRoot','indexPath','sessionRoots','observationRoot','observationTeams','historicalFrom','createdAt','expiresAt','initialMembers','legacyManifestPath','activityManifests'];
const pathKey=p=>process.platform==='win32'?localPath(p).toLowerCase():localPath(p);
const within=(root,path)=>{const r=relative(pathKey(root),pathKey(path));return r===''||!isAbsolute(r)&&!r.startsWith('..');};
const tuple=m=>hash([m.id,m.role,m.binding.hostId,m.binding.threadId,m.binding.revision??1]);
const rawSource=s=>({...s,bindings:s.bindings.map(({key,...b})=>b)});
const addMs=at=>new Date(Date.parse(at)+1).toISOString();
async function json(path,max=1024*1024){const info=await lstat(path);check(info.isFile()&&!info.isSymbolicLink()&&info.size<=max,'managed_config_invalid');return JSON.parse(await readFile(path,'utf8'));}
export function validateManagedPolicy(p){exact(p,POLICY);check(p.schemaVersion==='managed-metrics/v1'&&Number.isSafeInteger(p.revision)&&p.revision>0&&['active','revoked'].includes(p.status),'managed_policy_invalid');for(const k of ['policyId','teamId','hostId'])id(p[k]);for(const k of ['createdAt','historicalFrom','expiresAt'])time(p[k]);check(p.historicalFrom<=p.createdAt&&p.expiresAt>p.createdAt&&Date.parse(p.expiresAt)-Date.parse(p.historicalFrom)<=366*86400000,'managed_policy_range');
  check(typeof p.authorizationRef==='string'&&p.authorizationRef.length>0&&p.authorizationRef.length<=4000,'managed_authorization_required');for(const k of ['registryPath','statePath','managedRoot','indexPath','observationRoot'])check(typeof p[k]==='string'&&isAbsolute(p[k]),'managed_policy_path');check(Array.isArray(p.sessionRoots)&&p.sessionRoots.length>0&&p.sessionRoots.length<=4&&p.sessionRoots.every(r=>typeof r==='string'&&isAbsolute(r)),'managed_session_roots');
  check(p.sessionRoots.every(r=>!within(r,p.managedRoot)&&!within(p.managedRoot,r))&&!within(p.observationRoot,p.managedRoot)&&!within(p.managedRoot,p.observationRoot),'managed_root_overlap');check(Array.isArray(p.observationTeams)&&p.observationTeams.length<=1000&&p.observationTeams.includes(p.teamId)&&p.observationTeams.every(t=>{id(t);return true;}),'managed_observation_scope');check(Array.isArray(p.initialMembers)&&p.initialMembers.length<=200&&p.initialMembers.every(m=>{id(m);return true;}),'managed_member_limit');check(p.legacyManifestPath===null||typeof p.legacyManifestPath==='string'&&isAbsolute(p.legacyManifestPath),'managed_legacy_path');check(Array.isArray(p.activityManifests)&&p.activityManifests.length<=50&&p.activityManifests.every(f=>typeof f==='string'&&isAbsolute(f)),'managed_activity_scope');return p;}
export async function readManagedPolicy(path){return validateManagedPolicy(await json(resolve(path)));}
function policyState(p,at){return p.status==='revoked'?'revoked':at>=p.expiresAt?'expired':'active';}
function summary(p,at){return {policyId:p.policyId,revision:p.revision,status:policyState(p,at),permissionFrom:p.historicalFrom,permissionTo:p.expiresAt,capturedAt:at,recordingAuthority:'independent observedTeams allowlist; read-policy revocation does not revoke recording'};}
async function team(p,{read=readState}={}){const state=await read(p.statePath);check(state.team.id===p.teamId&&state.registry?.registryPath&&pathKey(state.registry.registryPath)===pathKey(p.registryPath),'managed_team_mismatch');const registry=await json(p.registryPath,8*1024*1024),native=registry.teams.find(t=>t.id===p.teamId);check(native&&native.revision===state.registry.teamRevision&&pathKey(native.runtime.statePath)===pathKey(p.statePath),'managed_registry_changed');
  const byId=new Map(native.members.map(m=>[m.id,m]));for(const m of state.members){const n=byId.get(m.id);check(n&&m.role===n.role&&m.lifecycle===n.lifecycle&&m.binding.hostId===n.binding.hostId&&m.binding.threadId===n.binding.threadId,'managed_binding_changed');}return {state,native,registry};}
const rosterProof=({state,native})=>hash([state.team.id,native.revision,native.members.map(m=>[m.id,m.role,m.lifecycle,m.binding]),state.registry.readyMemberIds]);
export async function planManagedMetrics(statePath,request,{now=()=>new Date().toISOString(),read=readState}={}){
  exact(request,['authorizationRef','hostId','managedRoot','indexPath','sessionRoots','observationRoot','observationTeams','historicalFrom','expiresAt','legacyManifestPath','activityManifests']);const state=await read(resolve(statePath));check(state.registry?.phase==='active','managed_link_required');const createdAt=now();time(createdAt);check(state.updatedAt<=createdAt,'managed_future_state');
  const p=validateManagedPolicy({schemaVersion:'managed-metrics/v1',policyId:'policy-'+hash([state.team.id,request.managedRoot,createdAt]).slice(0,24),revision:1,status:'active',...request,managedRoot:resolve(request.managedRoot),indexPath:localPath(request.indexPath),sessionRoots:request.sessionRoots.map(localPath),observationRoot:localPath(request.observationRoot),legacyManifestPath:request.legacyManifestPath?resolve(request.legacyManifestPath):null,activityManifests:request.activityManifests.map(f=>resolve(f)),teamId:state.team.id,registryPath:state.registry.registryPath,statePath:resolve(statePath),createdAt,initialMembers:state.members.filter(m=>m.lifecycle==='active').map(m=>m.id)}),captured=await team(p,{read});
  const plan={schemaVersion:'managed-plan/v1',policy:p,rosterProof:rosterProof(captured),expectedAbsent:true};return {...plan,planId:hash(plan)};
}
export async function applyManagedMetrics(plan,{read=readState}={}){exact(plan,['schemaVersion','policy','rosterProof','expectedAbsent','planId']);const {planId,...rest}=plan;check(plan.schemaVersion==='managed-plan/v1'&&planId===hash(rest),'managed_plan_invalid');const p=validateManagedPolicy(plan.policy);await mkdir(p.managedRoot,{recursive:true});return withFileLocks([join(p.managedRoot,'policy.lock')],async()=>{check(rosterProof(await team(p,{read}))===plan.rosterProof,'managed_plan_stale');const path=join(p.managedRoot,'policy.json');try{const current=await readManagedPolicy(path);check(hash(current)===hash(p),'managed_policy_conflict');return {status:'unchanged',policyPath:path};}catch(e){if(e.code!=='ENOENT')throw e;}await atomicWrite(path,JSON.stringify(p,null,2)+'\n',true);return {status:'enabled',policyPath:path};});}
async function legacySources(p){if(!p.legacyManifestPath)return {sources:[],tokenMembers:new Set()};const legacy=validateManifest(await json(p.legacyManifestPath),dirname(p.legacyManifestPath));check(legacy.teamId===p.teamId,'managed_legacy_team');const tokenMembers=new Set();for(const s of legacy.sources.filter(s=>s.kind==='usage-ledger')){const data=projectDocument(await json(s.path,8*1024*1024),s,legacy);for(const row of data.rows)if(row.kind==='token'&&row.memberId)tokenMembers.add(row.memberId);}return {sources:legacy.sources.map(rawSource),tokenMembers};}
function proofFrom(p,state,m,legacy,at){const matches=b=>b.memberId===m.id&&b.role===m.role&&b.hostId===m.binding.hostId&&b.threadId===m.binding.threadId&&b.bindingRevision===m.binding.revision;
  const known=legacy.sources.flatMap(s=>s.bindings).filter(matches).map(b=>({at:b.from,basis:'existing explicit binding grant'}));
  if(m.binding.revision===1){for(const r of state.rounds){if(!r.members.some(x=>x.id===m.id&&x.role===m.role&&x.binding.hostId===m.binding.hostId&&x.binding.threadId===m.binding.threadId))continue;const admissions=state.events.filter(e=>e.type==='admitRegistryMember'&&e.memberId===m.id&&e.roundId===r.id).map(e=>e.at);known.push({at:admissions.length?admissions.sort().at(-1):r.openedAt,basis:admissions.length?'exact recorded admission tuple':'initial recorded round tuple, revision1'});}}
  const earliest=known.sort((a,b)=>a.at.localeCompare(b.at))[0];let from=earliest?.at??at,basis=earliest?.basis??'first actual verification; no historical proof';if(!p.initialMembers.includes(m.id)&&from<p.createdAt){from=at;basis='new member first verification; no backfill before policy';}if(from<p.historicalFrom)from=p.historicalFrom;return {from,basis};}
function sourceBase(p,from,kind,path,sourceId,bindings,selection={taskId:null,roundId:null,turnIds:[],itemIds:[]}){return {sourceId,kind,path,adapterVersion:'v1',mutationPolicy:kind.endsWith('jsonl')?'append-only':kind==='team-context-root'?'immutable':'mutable',authorizedFrom:from,authorizedTo:p.expiresAt,bindings,selection,evidenceRef:p.authorizationRef+'; '+p.policyId,coverageAssertions:{status:'partial',evidenceRef:'explicit managed scope; actual snapshot cutoff separate; not full coverage'}};}
async function taskProducer(p,state,m,epoch,task){const producerDir=join(p.managedRoot,'producers'),activityDir=join(p.managedRoot,'activity');await mkdir(producerDir,{recursive:true});await mkdir(activityDir,{recursive:true});const suffix=hash([p.policyId,m.id,tuple(m),task.id]).slice(0,32),manifestPath=join(producerDir,suffix+'.json'),from=[epoch.from,task.assignedAt].filter(Boolean).sort().at(-1),binding={...epoch,from};delete binding.identity;delete binding.lastSeenAt;delete binding.basis;
  const source=sourceBase(p,from,'activity-jsonl',join(activityDir,suffix+'.jsonl'),'activity-'+suffix,[binding],{taskId:task.id,roundId:task.roundId,turnIds:[],itemIds:[]}),manifest={schemaVersion:'dashboard-sources/v1',teamId:p.teamId,registryId:state.registry.registryId,revision:1,authorizationRef:p.authorizationRef,sources:[source]};
  try{const old=await json(manifestPath);check(hash(old)===hash(manifest),'managed_producer_scope_changed');}catch(e){if(e.code!=='ENOENT')throw e;await atomicWrite(manifestPath,JSON.stringify(manifest,null,2)+'\n',true);}try{await writeFile(source.path,'',{flag:'wx'});}catch(e){if(e.code!=='EEXIST')throw e;}return {manifestPath,source};}
export async function ensureManagedMetrics(policyPath,{asOf=null,now=()=>new Date().toISOString(),read=readState,locate=locateSessions}={}){
  const p=await readManagedPolicy(policyPath);check(policyState(p,now())==='active','managed_policy_'+policyState(p,now()));const root=p.managedRoot;await mkdir(root,{recursive:true});
  return withFileLocks([join(root,'ensure.lock')],async()=>{check(hash(await readManagedPolicy(policyPath))===hash(p),'managed_policy_changed');const captured=await team(p,{read}),{state,native}=captured;asOf??=now();time(asOf);check(state.updatedAt<=asOf,'managed_future_state');let previous;try{previous=await json(join(root,'journal.json'));}catch(e){if(e.code!=='ENOENT')throw e;}check(!previous||previous.policyHash===hash(p),'managed_policy_changed');
    const legacy=await legacySources(p),epochs=structuredClone(previous?.epochs??[]),active=native.members.filter(m=>m.lifecycle==='active'&&m.binding.hostId===p.hostId&&state.registry.readyMemberIds.includes(m.id)),activeKeys=new Set(active.map(tuple)),issues=[],blocked=[];
    for(const old of epochs)if(old.to===p.expiresAt&&!activeKeys.has(old.identity)){old.to=old.lastSeenAt;issues.push({memberId:old.memberId,code:'managed_binding_gap',basis:'closed at last verified active point, not guessed change time'});}
    for(const m of active){let e=epochs.find(e=>e.identity===tuple(m)&&e.to===p.expiresAt);if(!e){const proof=proofFrom(p,state,m,legacy,asOf);e={memberId:m.id,hostId:m.binding.hostId,threadId:m.binding.threadId,role:m.role,bindingRevision:m.binding.revision,roleEpoch:'managed-'+hash([p.policyId,tuple(m),asOf]).slice(0,24),from:proof.from,to:p.expiresAt,evidenceRef:p.authorizationRef+'; '+proof.basis,identity:tuple(m),basis:proof.basis,lastSeenAt:asOf};epochs.push(e);}e.lastSeenAt=asOf;}
    let paths;try{paths=await locate(p.indexPath,active.map(m=>m.binding.threadId));}catch{paths=[];issues.push({code:'managed_index_unavailable'});}
    const cleanEpoch=e=>{const {identity,lastSeenAt,basis,...b}=e;return b;},sources=legacy.sources.filter(s=>!['team-context-root','recorded-state'].includes(s.kind)),oldNative=previous?.nativeSources??[],nativeSources=[];let budget=0;
    for(const m of active){const e=epochs.find(e=>e.identity===tuple(m)&&e.to===p.expiresAt),sourceId='session-'+hash([p.policyId,e.roleEpoch]).slice(0,24);try{check(budget<1048576,'managed_discovery_budget');const candidate=paths.find(x=>x.threadId===m.binding.threadId);check(candidate?.path,'managed_index_missing');const verified=await verifySessionCandidate(candidate,p.sessionRoots);budget+=verified.readBytes;
        let from=[e.from,verified.createdAt].sort().at(-1);if(legacy.tokenMembers.has(m.id)){const ends=legacy.sources.filter(s=>s.kind==='usage-ledger'&&s.bindings.some(b=>b.memberId===m.id&&b.hostId===e.hostId&&b.threadId===e.threadId&&b.role===e.role)).map(s=>s.authorizedTo);if(ends.length)from=[from,addMs(ends.sort().at(-1))].sort().at(-1);}
        const nativeSource=sourceBase(p,from,'codex-jsonl',verified.path,sourceId,[{...cleanEpoch(e),from}]);
        nativeSource.evidenceRef+='; native-schema-compatible-v2: explicit call identity, canonical UTC wire time, bounded compaction grammar, ambiguous duplicate outputs omitted';
        nativeSources.push(nativeSource);
      }catch(error){const code=/^[a-zA-Z0-9_-]{1,128}$/.test(error.code??'')?error.code:'managed_candidate_unavailable';issues.push({memberId:m.id,sourceId,code});const last=oldNative.find(s=>s.sourceId===sourceId);if(last){nativeSources.push(last);blocked.push(sourceId);}}
    }
    // Closed epochs retain their explicitly approved historical data/range;
    // changed/unknown current identities never borrow an old member's stream.
    for(const old of oldNative){if(nativeSources.some(s=>s.sourceId===old.sourceId))continue;const epoch=epochs.find(e=>e.roleEpoch===old.bindings[0]?.roleEpoch);if(epoch){nativeSources.push({...old,authorizedTo:epoch.to,bindings:old.bindings.map(b=>({...b,to:epoch.to}))});blocked.push(old.sourceId);}}
    sources.push(...nativeSources);const legacyRoot=legacy.sources.find(s=>s.kind==='team-context-root'&&pathKey(s.path)===pathKey(p.observationRoot)),rootBindings=[...(legacyRoot?.bindings??[])];
    for(const e of epochs){let from=e.from;const oldEnds=rootBindings.filter(b=>b.memberId===e.memberId&&b.role===e.role&&b.hostId===e.hostId&&b.threadId===e.threadId).map(b=>b.to);if(oldEnds.length)from=[from,addMs(oldEnds.sort().at(-1))].sort().at(-1);if(from<e.to)rootBindings.push({...cleanEpoch(e),from});}
    sources.push(sourceBase(p,legacyRoot?.authorizedFrom??p.historicalFrom,'team-context-root',p.observationRoot,'managed-team-context',rootBindings));sources.push(sourceBase(p,p.historicalFrom,'recorded-state',p.statePath,'managed-state',[]));
    const producers=[];for(const t of state.tasks.filter(t=>['assigned','executing','submitted','reviewing','rework','blocked'].includes(t.status))){for(const m of active.filter(m=>m.id===t.workerId||m.role!=='Worker')){const epoch=epochs.find(e=>e.identity===tuple(m)&&e.to===p.expiresAt),producer=await taskProducer(p,state,m,epoch,t);producers.push({taskId:t.id,memberId:m.id,...producer});}}
    for(const old of previous?.producers??[]){if(producers.some(p=>p.manifestPath===old.manifestPath))continue;const doc=validateManifest(await json(old.manifestPath),dirname(old.manifestPath));producers.push({...old,source:rawSource(doc.sources[0])});}
    for(const producer of producers){const snapshot=structuredClone(producer.source),epoch=epochs.find(e=>e.roleEpoch===snapshot.bindings[0].roleEpoch);if(epoch&&epoch.to<snapshot.bindings[0].to){snapshot.bindings[0].to=epoch.to;snapshot.authorizedTo=epoch.to;}sources.push(snapshot);}
    for(const ref of p.activityManifests){const grant=validateManifest(await json(ref),dirname(ref));check(grant.teamId===p.teamId,'managed_activity_team');for(const s of grant.sources){check(s.kind==='activity-jsonl','managed_activity_kind');sources.push(rawSource(s));}}
    const manifestPath=join(root,'manifest.json'),base={schemaVersion:'dashboard-sources/v1',teamId:p.teamId,registryId:state.registry.registryId,revision:1,authorizationRef:p.authorizationRef,managedPolicy:{policyId:p.policyId,path:resolve(policyPath)},sources};for(const s of sources){try{time(s.authorizedFrom);time(s.authorizedTo);}catch(e){throw Object.assign(e,{message:'Invalid managed source window '+s.sourceId+': '+s.authorizedFrom+' / '+s.authorizedTo});}}validateManifest(base,root);let oldManifest;try{oldManifest=await json(manifestPath);}catch(e){if(e.code!=='ENOENT')throw e;}const changed=!oldManifest||hash({...oldManifest,revision:1})!==hash(base);base.revision=changed?(oldManifest?.revision??0)+1:oldManifest.revision;
    check(rosterProof(await team(p,{read}))===rosterProof(captured)&&hash(await readManagedPolicy(policyPath))===hash(p),'managed_ensure_stale');if(changed)await atomicWrite(manifestPath,JSON.stringify(base,null,2)+'\n');
    const journal={schemaVersion:'managed-journal/v1',policyHash:hash(p),asOf,stateVersion:state.version,teamRevision:native.revision,epochs,nativeSources,producers:producers.map(({source,...v})=>v),issues,blockedSourceIds:blocked,metadataReadBytes:budget};await atomicWrite(join(root,'journal.json'),JSON.stringify(journal,null,2)+'\n');return {policy:p,manifestPath,cache:join(root,'cache'),journal,changed,summary:{...summary(p,asOf),issues,currentBindings:active.map(m=>({memberId:m.id,identityHash:hash([m.id,m.role,m.binding.hostId,m.binding.threadId]),bindingRevision:m.binding.revision}))}};
  });
}
async function blockedSnapshot(p,asOf,status,code,cache=join(p.managedRoot,'cache')){return markStatsBlocked(cache,{...summary(p,asOf),status,issue:code},asOf);}
export async function refreshManagedMetrics(policyPath,options={}){const p=await readManagedPolicy(policyPath),cache=options.cache?resolve(options.cache):join(p.managedRoot,'cache');let asOf=options.asOf??null;const actual=()=>options.now?.()??new Date().toISOString();check(within(p.managedRoot,cache)&&cache!==p.managedRoot,'managed_cache_scope');return withFileLocks([join(p.managedRoot,'policy.lock')],async()=>{check(hash(await readManagedPolicy(policyPath))===hash(p),'managed_policy_changed');if(policyState(p,actual())!=='active')return blockedSnapshot(p,asOf??actual(),policyState(p,actual()),'managed_policy_'+policyState(p,actual()),cache);let ensured;try{ensured=await ensureManagedMetrics(policyPath,{...options,asOf});asOf=ensured.journal.asOf;}catch(error){try{await readStatsIndex(cache);}catch(e){if(e.code==='ENOENT')throw error;throw e;}return blockedSnapshot(p,asOf??actual(),'unavailable','managed_ensure_unavailable',cache);}
  const permitted=async()=>{const current=await readManagedPolicy(policyPath);return hash(current)===hash(p)&&policyState(current,options.now?.()??new Date().toISOString())==='active';};
  try{return await refreshStats(ensured.manifestPath,cache,{...options,asOf,managedApproved:true,managedPolicy:ensured.summary,allowedObservationTeams:p.observationTeams,strictObservationBindings:true,blockedSourceIds:ensured.journal.blockedSourceIds,sourceGate:async()=>({allow:await permitted(),code:'managed_policy_changed'}),beforeCommit:async index=>{await options.beforeCommit?.(index);check(await permitted(),'managed_policy_changed');}});}catch(error){const latest=await readManagedPolicy(policyPath);return blockedSnapshot(latest,asOf,policyState(latest,asOf)==='active'?'unavailable':policyState(latest,asOf),'managed_collection_unavailable',cache);}});}
export async function prepareManagedStep(policyPath,request,options={}){exact(request,['hostId','threadId','taskId','roundId','stepId','evidenceRef']);const p=await readManagedPolicy(policyPath),asOf=options.asOf??new Date().toISOString();check(policyState(p,asOf)==='active','managed_policy_inactive');const ensured=await ensureManagedMetrics(policyPath,{...options,asOf}),{state}=await team(p,options),proof=validateObservationContext(state,request,{scope:'task',team_id:p.teamId,task_id:request.taskId,round_id:request.roundId,step_id:request.stepId},{now:asOf}),task=state.tasks.find(t=>t.id===request.taskId);check(proof.validation.role!=='Worker'||['executing','rework'].includes(task.status),'managed_task_not_executing');const entry=ensured.journal.producers.find(x=>x.taskId===request.taskId&&x.memberId===proof.validation.memberId);check(entry,'managed_task_not_active');const manifest=await json(entry.manifestPath),b=manifest.sources[0].bindings[0];check(request.hostId===b.hostId&&request.threadId===b.threadId&&request.roundId===manifest.sources[0].selection.roundId,'managed_step_binding_mismatch');return {policy:p,manifestPath:entry.manifestPath,sourceId:manifest.sources[0].sourceId,context:{teamId:p.teamId,memberId:b.memberId,hostId:b.hostId,threadId:b.threadId,bindingRevision:b.bindingRevision,roleEpoch:b.roleEpoch,role:b.role,taskId:request.taskId,roundId:request.roundId,stepId:request.stepId,assurance:b.role==='Worker'?'worker-declared':'operator-declared',evidenceRef:request.evidenceRef}};}
export async function runManagedStep(policyPath,request,receiptPath,command,options={}){const entry=await prepareManagedStep(policyPath,request,options);return runActivityStep(entry.policy.statePath,entry.manifestPath,entry.sourceId,request,receiptPath,command,options);}
export async function managedStepRequest(policyPath,taskId,stepId,{threadId=process.env.CODEX_THREAD_ID,...options}={}){id(taskId);id(stepId);id(threadId);const p=await readManagedPolicy(policyPath),{state}=await team(p,options),task=state.tasks.find(t=>t.id===taskId);check(task,'managed_task_unknown');return {hostId:p.hostId,threadId,taskId,roundId:task.roundId,stepId,evidenceRef:p.policyId+': explicit '+stepId};}
export async function beginManagedActivity(policyPath,request,receiptPath,options={}){const entry=await prepareManagedStep(policyPath,request,options);const result=await beginActivity(entry.manifestPath,entry.sourceId,entry.context,receiptPath,options);return {...result,producerManifest:entry.manifestPath};}
export async function endManagedActivity(policyPath,taskId,receiptPath,options={}){const receipt=await json(resolve(receiptPath),65536),request=await managedStepRequest(policyPath,taskId,receipt.beginEvent.stepId,options),p=await readManagedPolicy(policyPath),{state}=await team(p,options);const proof=validateObservationContext(state,request,{scope:'task',team_id:p.teamId,task_id:taskId,round_id:request.roundId,step_id:request.stepId});check(proof.validation.memberId===receipt.beginEvent.memberId&&request.hostId===receipt.beginEvent.hostId&&request.threadId===receipt.beginEvent.threadId,'managed_step_binding_mismatch');check(within(join(p.managedRoot,'producers'),receipt.manifestPath),'managed_step_manifest_scope');return endActivity(receipt.manifestPath,receiptPath,options);}
export async function revokeManagedMetrics(policyPath){const p=await readManagedPolicy(policyPath);return withFileLocks([join(p.managedRoot,'policy.lock')],async()=>{const current=await readManagedPolicy(policyPath);check(hash(current)===hash(p),'managed_policy_changed');if(p.status==='revoked')return {status:'unchanged'};await atomicWrite(policyPath,JSON.stringify({...p,status:'revoked',revision:p.revision+1},null,2)+'\n');return {status:'revoked',recordingUnchanged:true};});}
export async function enableObservationTeams(configPath,policyPaths){const teams=[];for(const ref of policyPaths){const p=await readManagedPolicy(ref);check(policyState(p,new Date().toISOString())==='active','managed_policy_inactive');teams.push(p.teamId);}return withFileLocks([configPath+'.lock'],async()=>{const old=await json(configPath,65536);exact(old,['schemaVersion','observedTeams']);check(old.schemaVersion===1&&Array.isArray(old.observedTeams),'managed_observation_config');const next={schemaVersion:1,observedTeams:[...new Set([...old.observedTeams,...teams])].sort()};if(hash(old)!==hash(next))await atomicWrite(configPath,JSON.stringify(next,null,2)+'\n');return {preserved:old.observedTeams,enabled:next.observedTeams,recordingAuthority:'separate persistent allowlist; collector policy only controls reads'};});}
